README.md
URL's moved so accordingly changing the url for user guide and java docs.
=> Fixing Readme URL's

README.md
potentially mixup of attributes - the view backing the findByLastname method should emit lastname not firstname
=> fixed potential typo in readme.md

pom.xml, src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java, src/main/java/org/springframework/data/couchbase/config/BeanNames.java, src/main/java/org/springframework/data/couchbase/config/CouchbaseEnvironmentNoShutdownProxy.java, src/main/java/org/springframework/data/couchbase/config/CouchbaseJmxParser.java, src/main/java/org/springframework/data/couchbase/config/CouchbaseNamespaceHandler.java, src/main/java/org/springframework/data/couchbase/config/CouchbaseTemplateParser.java, src/main/java/org/springframework/data/couchbase/core/CouchbaseOperations.java, src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplate.java, src/main/java/org/springframework/data/couchbase/core/mapping/Document.java, src/main/java/org/springframework/data/couchbase/core/mapping/Field.java, src/main/java/org/springframework/data/couchbase/monitor/ClientInfo.java, src/main/java/org/springframework/data/couchbase/monitor/ClusterInfo.java, src/main/java/org/springframework/data/couchbase/template/package-info.java
For xml configuration, only the basic parsers have been implemented.
Prepared an `AbstractCouchbaseConfiguration` `@Configuration` that allows to create beans for the `CouchbaseEnvironment` (including sharing one from outside of the Spring context), the `Cluster` and the `Bucket`.
Skeletal implementations of `CouchbaseOperations` and `CouchbaseTemplate` for compilation purposes.
=> basic configuration (xml parsers and @Configuration)

src/integration/java/org/springframework/data/couchbase/IntegrationTestApplicationConfig.java, src/integration/java/org/springframework/data/couchbase/config/CouchbaseTemplateParserIntegrationTests.java, src/integration/java/org/springframework/data/couchbase/core/CouchbaseTemplateTests.java, src/integration/java/org/springframework/data/couchbase/monitor/ClientInfoTests.java, src/integration/java/org/springframework/data/couchbase/monitor/ClusterInfoTests.java, src/integration/resources/configurations/couchbase-multi-bucket-bean.xml, src/integration/resources/configurations/couchbase-template-bean.xml, src/integration/resources/configurations/couchbase-template-with-translation-service-bean.xml, src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplate.java, src/test/java/org/springframework/data/couchbase/UnitTestApplicationConfig.java, src/test/java/org/springframework/data/couchbase/core/mapping/CustomConvertersTests.java, src/test/java/org/springframework/data/couchbase/core/mapping/MappingCouchbaseConverterTests.java
integration tests have been better separated from unit tests (and each have their own configuration).
new integration tests have been put in place for templateParser and monitor classes.
=> [SDK2] fix template constructor order + improve tests

src/integration/java/org/springframework/data/couchbase/core/CouchbaseTemplateTests.java, src/main/java/org/springframework/data/couchbase/core/CouchbaseExceptionTranslator.java, src/main/java/org/springframework/data/couchbase/core/CouchbaseQueryExecutionException.java, src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplate.java, src/main/java/org/springframework/data/couchbase/core/convert/translation/JacksonTranslationService.java, src/main/java/org/springframework/data/couchbase/core/convert/translation/TranslationService.java, src/test/java/org/springframework/data/couchbase/core/convert/translation/JacksonTranslationServiceTests.java
implement findByQuery by allowing TranslationService to unmarshall an adhoc fragment of JSON (the N1QL rows).
added error handling for both findByView and findByQuery.
also fixed the template trying to set a Version field even if no such field is declared in the EntityClass.
=> [SDK2] findByXXXQuery improvements

src/integration/java/org/springframework/data/couchbase/core/CouchbaseTemplateTests.java, src/integration/java/org/springframework/data/couchbase/repository/SimpleCouchbaseRepositoryTests.java, src/integration/java/org/springframework/data/couchbase/repository/UserRepository.java, src/main/java/org/springframework/data/couchbase/core/CouchbaseOperations.java, src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplate.java, src/main/java/org/springframework/data/couchbase/core/view/N1QL.java, src/main/java/org/springframework/data/couchbase/repository/query/AbstractN1qlBasedQuery.java, src/main/java/org/springframework/data/couchbase/repository/query/CouchbaseQueryMethod.java, src/main/java/org/springframework/data/couchbase/repository/query/StringN1qlBasedQuery.java, src/main/java/org/springframework/data/couchbase/repository/query/ViewBasedCouchbaseQuery.java, src/main/java/org/springframework/data/couchbase/repository/support/CouchbaseRepositoryFactory.java, src/test/java/org/springframework/data/couchbase/UnitTestApplicationConfig.java, src/test/java/org/springframework/data/couchbase/repository/query/AbstractN1qlBasedQueryTest.java, src/test/java/org/springframework/data/couchbase/repository/query/StringN1QlBasedQueryTest.java
The annotation allows to execute N1QL queries that are provided inline. For ease of use, one can use the placeholder $SELECT_ENTITY$ instead of writing the SELECT and FROM clauses.
QueryParams passed in as a method parameter will be used to enrich the Query. Other parameters on the annotated method will be used as values for positional placeholders in the statement.
The template's findByN1QL now expect enough data to reconstruct the full CouchbaseDocument (including ID and CAS), the ad hoc version of it has been renamed findByN1QLProjection.
=> DATACOUCH-136 - Add @N1QL query annotation.

src/integration/java/org/springframework/data/couchbase/core/CouchbaseTemplateTests.java, src/integration/java/org/springframework/data/couchbase/repository/SimpleCouchbaseRepositoryTests.java, src/integration/java/org/springframework/data/couchbase/repository/UserRepository.java, src/main/java/org/springframework/data/couchbase/config/CouchbaseNamespaceHandler.java, src/main/java/org/springframework/data/couchbase/core/CouchbaseOperations.java, src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplate.java, src/main/java/org/springframework/data/couchbase/core/mapping/CouchbasePersistentProperty.java, src/main/java/org/springframework/data/couchbase/core/view/N1QL.java, src/main/java/org/springframework/data/couchbase/repository/query/AbstractN1qlBasedQuery.java, src/main/java/org/springframework/data/couchbase/repository/query/CouchbaseQueryMethod.java, src/main/java/org/springframework/data/couchbase/repository/query/N1qlQueryCreator.java, src/main/java/org/springframework/data/couchbase/repository/query/PartTreeN1qlBasedQuery.java, src/main/java/org/springframework/data/couchbase/repository/query/StringN1qlBasedQuery.java, src/main/java/org/springframework/data/couchbase/repository/query/ViewBasedCouchbaseQuery.java, src/main/java/org/springframework/data/couchbase/repository/support/CouchbaseRepositoryFactory.java, src/test/java/org/springframework/data/couchbase/UnitTestApplicationConfig.java, src/test/java/org/springframework/data/couchbase/repository/query/AbstractN1qlBasedQueryTest.java, src/test/java/org/springframework/data/couchbase/repository/query/N1qlQueryCreatorTest.java, src/test/java/org/springframework/data/couchbase/repository/query/StringN1QlBasedQueryTest.java
Abstracted the N1QL-based variants in AbstractN1qlBasedQuery. This implementation doesn't recognize QueryParams or QueryPlan anymore in the method parameters so that the method signatures are not store-dependent.
Added query derivation from PartTree to N1QL query, using N1qlQueryCreator.
Unit tested the mapping between a Part.Type and the corresponding N1QL Expression.
=> DATACOUCH-137 - queryDerivation for N1QL annotated methods.

src/integration/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryViewTests.java, src/integration/java/org/springframework/data/couchbase/repository/CustomUserRepository.java, src/integration/java/org/springframework/data/couchbase/repository/SimpleCouchbaseRepositoryTests.java, src/integration/java/org/springframework/data/couchbase/repository/UserRepository.java, src/main/java/org/springframework/data/couchbase/core/view/Query.java, src/main/java/org/springframework/data/couchbase/core/view/View.java, src/main/java/org/springframework/data/couchbase/repository/query/CouchbaseQueryMethod.java, src/main/java/org/springframework/data/couchbase/repository/query/N1qlQueryCreator.java, src/main/java/org/springframework/data/couchbase/repository/query/StringN1qlBasedQuery.java, src/main/java/org/springframework/data/couchbase/repository/query/ViewBasedCouchbaseQuery.java, src/main/java/org/springframework/data/couchbase/repository/support/CouchbaseRepositoryFactory.java
The @N1QL annotation was changed to @Query, for discoverability and also
convey that this is now the preferred method.
Order is now view if @View present, N1ql inline if @Query present with
a Statement, N1ql query derivation if @Query without attribute or no
annotation.
@View can be without attribute in order to compute the view
and design document from method name.
=> DATACOUCH-141 - Change query lookup order and make N1QL default.

src/integration/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryViewListener.java, src/integration/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryViewTests.java, src/integration/java/org/springframework/data/couchbase/repository/CustomUserRepository.java, src/integration/java/org/springframework/data/couchbase/repository/User.java, src/main/java/org/springframework/data/couchbase/core/view/View.java, src/main/java/org/springframework/data/couchbase/repository/query/CouchbaseQueryMethod.java, src/main/java/org/springframework/data/couchbase/repository/query/ViewBasedCouchbaseQuery.java, src/main/java/org/springframework/data/couchbase/repository/query/ViewQueryCreator.java
@View can now trigger a basic query derivation. If viewName's explicitly
set, query derivation is attempted. Otherwise, no derivation is made but
instead the viewName is guessed by using the method name and removing a
"find" or "count" prefix.
Methods prefixed with "count" (and in general detected as count
projections) will trigger a reduce on the view.
=> DATACOUCH-139 - Add limited support for @View query derivation.

src/integration/java/org/springframework/data/couchbase/repository/Party.java, src/integration/java/org/springframework/data/couchbase/repository/PartyRepository.java, src/integration/java/org/springframework/data/couchbase/repository/QueryDerivationConversionListener.java, src/integration/java/org/springframework/data/couchbase/repository/QueryDerivationConversionTests.java, src/main/java/org/springframework/data/couchbase/core/convert/AbstractCouchbaseConverter.java, src/main/java/org/springframework/data/couchbase/core/convert/CouchbaseConverter.java, src/main/java/org/springframework/data/couchbase/core/convert/DateConverters.java, src/main/java/org/springframework/data/couchbase/core/mapping/CouchbaseSimpleTypes.java, src/main/java/org/springframework/data/couchbase/repository/query/ConvertingIterator.java, src/main/java/org/springframework/data/couchbase/repository/query/N1qlQueryCreator.java, src/main/java/org/springframework/data/couchbase/repository/query/ViewBasedCouchbaseQuery.java, src/main/java/org/springframework/data/couchbase/repository/query/ViewQueryCreator.java
When deriving a query, use the CouchbaseConverter to transform the parameters for fields that would be converted upon storage.
Reworked the DateConverters so that reading conversion is done from any Number (since N1QL may return longs in Double scientific notation for example).
=> DATACOUCH-140 - Use Converter to match query params and stored values.

src/integration/java/org/springframework/data/couchbase/config/CouchbaseTemplateParserIntegrationTests.java, src/integration/java/org/springframework/data/couchbase/core/CouchbaseTemplateViewListener.java, src/integration/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryViewListener.java, src/integration/java/org/springframework/data/couchbase/repository/QueryDerivationConversionListener.java, src/integration/java/org/springframework/data/couchbase/repository/SimpleCouchbaseRepositoryListener.java, src/integration/java/org/springframework/data/couchbase/repository/cdi/CouchbaseClusterInfoProducer.java, src/integration/java/org/springframework/data/couchbase/repository/feature/FeatureDetectionRepositoryTests.java, src/integration/java/org/springframework/data/couchbase/repository/feature/FeatureDetectionTestApplicationConfig.java, src/integration/java/org/springframework/data/couchbase/repository/feature/ViewOnlyUserRepository.java, src/integration/resources/configurations/couchbase-multi-bucket-bean.xml, src/integration/resources/configurations/couchbase-template-bean.xml, src/integration/resources/configurations/couchbase-template-with-translation-service-bean.xml, src/integration/resources/configurations/couchbase-typekey.xml, src/main/asciidoc/configuration.adoc, src/main/asciidoc/repository.adoc, src/main/asciidoc/template.adoc, src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java, src/main/java/org/springframework/data/couchbase/config/BeanNames.java, src/main/java/org/springframework/data/couchbase/config/CouchbaseClusterInfoFactoryBean.java, src/main/java/org/springframework/data/couchbase/config/CouchbaseClusterInfoParser.java, src/main/java/org/springframework/data/couchbase/config/CouchbaseNamespaceHandler.java, src/main/java/org/springframework/data/couchbase/core/CouchbaseOperations.java, src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplate.java, src/main/java/org/springframework/data/couchbase/core/UnsupportedCouchbaseFeatureException.java, src/main/java/org/springframework/data/couchbase/repository/query/ViewBasedCouchbaseQuery.java, src/main/java/org/springframework/data/couchbase/repository/support/CouchbaseRepositoryFactory.java, src/main/java/org/springframework/data/couchbase/repository/support/CouchbaseRepositoryFactoryBean.java, src/main/resources/org/springframework/data/couchbase/config/spring-couchbase-2.0.xsd, src/test/java/org/springframework/data/couchbase/UnitTestApplicationConfig.java
Detect N1QL is not available at configuration time for the repositories and at runtime for the template. This throws a UnsupportedCouchbaseFeatureException.
The ClusterInfo is captured at bootstrap and used to determine if the feature is available. The xml configuration will need the ClusterInfo-related credentials to be provided explicitly.
=> DATACOUCH-144 - Detect N1QL dependency and fail fast if not available.

README.md, src/main/asciidoc/repository.adoc, src/main/java/org/springframework/data/couchbase/repository/support/SimpleCouchbaseRepository.java
In the SimpleCouchbaseRepository the guessed design document was lowercase of the entity class, whereas in ViewBasedCouchbaseQuery it is uncapitalized (only first letter is lowercase).
This has been made consistent, using the uncapitalize method. The doc now reflects that and explicitly have examples with camel case classes (UserInfo instead of User).
=> DATACOUCH-154 - Guess design doc as uncapitalized class name.

src/integration/java/org/springframework/data/couchbase/repository/Item.java, src/integration/java/org/springframework/data/couchbase/repository/ItemRepository.java, src/integration/java/org/springframework/data/couchbase/repository/N1qlCrudRepositoryTests.java, src/integration/java/org/springframework/data/couchbase/repository/PartyRepository.java, src/main/asciidoc/repository.adoc, src/main/java/org/springframework/data/couchbase/core/convert/CouchbaseConverter.java, src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java, src/main/java/org/springframework/data/couchbase/repository/query/N1qlQueryCreator.java, src/main/java/org/springframework/data/couchbase/repository/query/PartTreeN1qlBasedQuery.java, src/main/java/org/springframework/data/couchbase/repository/query/StringN1qlBasedQuery.java, src/test/java/org/springframework/data/couchbase/repository/query/StringN1QlBasedQueryTest.java
The generated N1QL queries currently don't filter on the type at all.
Add a criteria to the WHERE clause that checks the field holding type information is matching the entity fully qualified class name.
Add a placeholder for inline N1QL queries that can be replaced by the same type information criteria.
=> DATACOUCH-156 - Make generated N1QL queries filter on the type field.

src/main/java/org/springframework/data/couchbase/core/mapping/BasicCouchbasePersistentEntity.java, src/main/java/org/springframework/data/couchbase/core/mapping/CouchbaseDocument.java, src/main/java/org/springframework/data/couchbase/core/mapping/CouchbasePersistentEntity.java, src/main/java/org/springframework/data/couchbase/core/mapping/Document.java, src/test/java/org/springframework/data/couchbase/core/mapping/BasicCouchbasePersistentEntityTests.java
The Document annotation now also support explicitly giving a TimeUnit for the expiry, ensuring the framework will correctly convert that to the expected Couchbase format.
pinging @daschl for review :smile:
=> DATACOUCH-158 - Allow more explicit expiry unit

src/integration/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryViewTests.java, src/integration/java/org/springframework/data/couchbase/repository/N1qlCouchbaseRepositoryTests.java, src/integration/java/org/springframework/data/couchbase/repository/N1qlCrudRepositoryTests.java, src/integration/java/org/springframework/data/couchbase/repository/PageAndSliceTests.java, src/integration/java/org/springframework/data/couchbase/repository/QueryDerivationConversionTests.java, src/integration/java/org/springframework/data/couchbase/repository/SimpleCouchbaseRepositoryTests.java, src/integration/java/org/springframework/data/couchbase/repository/feature/FeatureDetectionRepositoryTests.java, src/integration/java/org/springframework/data/couchbase/repository/wiring/RepositoryTemplateWiringTests.java, src/main/asciidoc/repository.adoc, src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java, src/main/java/org/springframework/data/couchbase/config/BeanNames.java, src/main/java/org/springframework/data/couchbase/repository/cdi/CouchbaseRepositoryBean.java, src/main/java/org/springframework/data/couchbase/repository/config/CouchbaseRepositoryConfigurationExtension.java, src/main/java/org/springframework/data/couchbase/repository/config/EnableCouchbaseRepositories.java, src/main/java/org/springframework/data/couchbase/repository/config/RepositoryOperationsMapping.java, src/main/java/org/springframework/data/couchbase/repository/support/CouchbaseRepositoryFactory.java, src/main/java/org/springframework/data/couchbase/repository/support/CouchbaseRepositoryFactoryBean.java
Added a configuration bean that allows to express what `CouchbaseOperations` each repository should use, individually or by domain type.
=> DATACOUCH-161 - Support repos with different buckets

src/integration/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryViewListener.java, src/integration/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryViewTests.java, src/integration/java/org/springframework/data/couchbase/repository/CustomUserRepository.java, src/main/asciidoc/migrating.adoc, src/main/asciidoc/repository.adoc, src/main/java/org/springframework/data/couchbase/core/view/View.java, src/main/java/org/springframework/data/couchbase/repository/query/ViewBasedCouchbaseQuery.java, src/main/java/org/springframework/data/couchbase/repository/query/ViewQueryCreator.java
Detection whether or not reduce should be activated is now centralized. Triggers are:
- using the `count` prefix instead of `find` in method name
- setting `reduce = true` in the `View` annotation explicitly.
The reduce can thus be returning any kind of value (added an integration example with `_stats`), which is now properly documented.
=> DATACOUCH-168 - Support and document all reduce functions

src/integration/java/org/springframework/data/couchbase/repository/N1qlCouchbaseRepositoryTests.java, src/main/java/org/springframework/data/couchbase/repository/support/N1qlCouchbaseRepository.java
Default consistency from template wasn't used in PagingAndSorting findAll methods.
=> DATACOUCH-172 - Fix PagingAndSorting consistency

src/integration/java/org/springframework/data/couchbase/repository/wiring/RepositoryTemplateWiringTests.java, src/main/asciidoc/repository.adoc, src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java, src/main/java/org/springframework/data/couchbase/repository/config/RepositoryOperationsMapping.java, src/main/java/org/springframework/data/couchbase/repository/support/CouchbaseRepositoryFactory.java, src/main/java/org/springframework/data/couchbase/repository/support/CouchbaseRepositoryFactoryBean.java
The configuration step made it look like a new mapping was necessary in overrides, whereas it is actually possible and clearer to mutate the base mapping.
Added a convenience method to get the MappingContext from the repository mapping.
=> DATACOUCH-161 - Improve multitemplate mapping configuration

src/integration/java/org/springframework/data/couchbase/repository/DimensionalQueryTests.java, src/integration/java/org/springframework/data/couchbase/repository/Party.java, src/main/asciidoc/repository.adoc, src/main/java/org/springframework/data/couchbase/repository/query/SpatialViewBasedQuery.java, src/main/java/org/springframework/data/couchbase/repository/query/SpatialViewQueryCreator.java, src/main/java/org/springframework/data/couchbase/repository/query/support/GeoUtils.java, src/test/resources/logback.xml
So far with geo queries a bounding box approximation was performed on Circle and Polygon queries (since Couchbase internally only supports Bounding Box queries).
It was confusing since in previous iteration it was up to the user to remove these false positives "after the fact" in code calling the repository.
This change allows for the framework to retain enough information to perform false positives elimination automatically and transparently for the user.
=> DATACOUCH-176 - Geo false positive autoelimination

src/main/asciidoc/repository.adoc, src/main/java/org/springframework/data/couchbase/repository/support/SimpleCouchbaseRepository.java, src/test/java/org/springframework/data/couchbase/repository/RepositoryIndexUsageTest.java
The CRUD methods that are backed by a view in SimpleCouchbaseRepository now take the default view consistency into account.
This includes findAll(), findAll(keys), count() and deleteAll().
PagingAndSortingRepository findAll methods already took the default N1QL consistency into account.
This is verified in an unit test and has been made more explicit in the repository documentation.
=> DATACOUCH-185 - view-based CRUD methods use default consistency

src/main/asciidoc/repository.adoc, src/main/java/org/springframework/data/couchbase/core/CouchbaseExceptionTranslator.java, src/main/java/org/springframework/data/couchbase/core/CouchbaseOperations.java, src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplate.java, src/main/java/org/springframework/data/couchbase/repository/support/SimpleCouchbaseRepository.java, src/test/java/org/springframework/data/couchbase/repository/RepositoryIndexUsageTest.java
This commit ensures that methods in the template and the repository base classes are correctly ignoring documents that have been deleted but are still identified by the view due to using weak consistency (Stale.TRUE).
FindByView in template now ignores null rows in its result list. It also correctly forces the includeDocs parameter in order not to risk a bad transcoding of the document (javadoc clarified).
DeleteAll in the repository CRUD implementation will correctly detect attempts at deleting a non-existing document (DocumentDoesNotExistException is also correctly mapped to a Spring Data exception now).
DeleteAll behavior with DataRetrievalFailureException is tested in RepositoryIndexUsageTest.
=> DATACOUCH-186 - Index-backed methods safe from deleted stales

src/integration/java/org/springframework/data/couchbase/repository/N1qlCrudRepositoryTests.java, src/integration/java/org/springframework/data/couchbase/repository/PartyRepository.java, src/main/asciidoc/repository.adoc, src/main/java/org/springframework/data/couchbase/repository/query/AbstractN1qlBasedQuery.java, src/main/java/org/springframework/data/couchbase/repository/query/CouchbaseQueryMethod.java, src/main/java/org/springframework/data/couchbase/repository/query/PartTreeN1qlBasedQuery.java, src/main/java/org/springframework/data/couchbase/repository/query/StringN1qlBasedQuery.java, src/test/java/org/springframework/data/couchbase/repository/query/AbstractN1qlBasedQueryTest.java
This change allows simple projections to types long, boolean, String when an inline N1QL query uses an aggregation function like AVG, COUNT.
The projection's result must be a single row with a single key/value pair in the N1QL response. Only the value gets returned.
=> DATACOUCH-187 - Allow counting queries and single projections.

src/integration/java/org/springframework/data/couchbase/repository/index/IndexedFooRepository.java, src/integration/java/org/springframework/data/couchbase/repository/index/IndexedRepositoryTestListener.java, src/integration/java/org/springframework/data/couchbase/repository/index/IndexedRepositoryTests.java, src/main/asciidoc/repository.adoc, src/main/java/org/springframework/data/couchbase/core/query/ViewIndexed.java, src/main/java/org/springframework/data/couchbase/repository/support/IndexManager.java
The generated view's default map function now emits meta.id so that CRUD findAll(ids) works.
The default value for the view name is now "all".
The ViewIndexed isn't documented as applicable to METHODs (deferred feature).
=> DATACOUCH-196 - Fix ViewIndexed generated map and improve usability

src/integration/java/org/springframework/data/couchbase/IntegrationTestApplicationConfig.java, src/integration/java/org/springframework/data/couchbase/repository/extending/base/RepositoryBaseTest.java, src/integration/java/org/springframework/data/couchbase/repository/extending/method/RepositoryCustomMethodTest.java, src/integration/java/org/springframework/data/couchbase/repository/feature/FeatureDetectionTestApplicationConfig.java, src/integration/java/org/springframework/data/couchbase/repository/index/AnotherIndexedUserRepository.java, src/integration/java/org/springframework/data/couchbase/repository/index/IndexedRepositoryTests.java, src/integration/java/org/springframework/data/couchbase/repository/wiring/RepositoryTemplateWiringTests.java, src/main/asciidoc/repository.adoc, src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java, src/main/java/org/springframework/data/couchbase/config/CouchbaseIndexManagerParser.java, src/main/java/org/springframework/data/couchbase/repository/support/IndexManager.java, src/main/resources/org/springframework/data/couchbase/config/spring-couchbase-2.0.xsd, src/test/java/org/springframework/data/couchbase/UnitTestApplicationConfig.java
In addition to annotating the repository with xxxIndexed annotations, user must now opt-in to the feature by redefining the indexManager bean in the configuration. This is so production use of this feature is actively discouraged.
=> DATACOUCH-199 - Make automatic index creation opt-in

src/integration/java/org/springframework/data/couchbase/config/CouchbaseTemplateParserIntegrationTests.java, src/integration/resources/configurations/couchbase-consistency.xml, src/main/asciidoc/repository.adoc, src/main/java/org/springframework/data/couchbase/core/query/Consistency.java
Formerly UPDATE_AFTER, but the inconsistent view this would give eg. while writing tests or exploring Spring Data Couchbase was confusing to users.
cc. @snicoll for review, related to spring-projects/spring-boot#5159
=> DATACOUCH-209 - Change default Consistency to READ_YOUR_OWN_WRITES

src/integration/java/org/springframework/data/couchbase/config/CouchbaseTemplateParserIntegrationTests.java, src/integration/java/org/springframework/data/couchbase/core/CouchbaseTemplateViewListener.java, src/integration/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryViewListener.java, src/integration/java/org/springframework/data/couchbase/repository/PartyPopulatorListener.java, src/integration/java/org/springframework/data/couchbase/repository/SimpleCouchbaseRepositoryListener.java, src/integration/java/org/springframework/data/couchbase/repository/index/IndexedRepositoryTestListener.java, src/main/java/org/springframework/data/couchbase/config/BeanNames.java, src/main/java/org/springframework/data/couchbase/repository/config/EnableCouchbaseRepositories.java
This makes all bean names public constants, which can be used in Conditional annotation in Spring Boot for instance (cc @snicoll).
=> DATACOUCH-207 - Makes all BeanNames constants public

src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java, src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseDataConfiguration.java, src/main/java/org/springframework/data/couchbase/config/CouchbaseConfigurer.java
Rather than having to extend a few methods from the base Configuration
class, this commit introduces a strategy interface to gather them.
`CouchbaseConfigurer` represents all the components that the Spring Data
integration requires.
=> Introduce CouchbaseConfigurer

src/integration/java/org/springframework/data/couchbase/config/AbstractCouchbaseDataConfigurationTest.java, src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java, src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseDataConfiguration.java, src/main/java/org/springframework/data/couchbase/config/CouchbaseConfigurer.java
The aim here is to facilitate integration with Spring Boot while allowing apps to have a dependency on the Couchbase SDK (`Bucket` and `Cluster`) without necessarily pulling in Spring Data Couchbase.
Pinging @daschl @snicoll @olivergierke for quick review (as per the ongoing email thread).
=> DATACOUCH-215 - Separate config concerns between SDK core and Spring Data

src/integration/java/org/springframework/data/couchbase/repository/auditing/AuditedApplicationConfig.java, src/integration/java/org/springframework/data/couchbase/repository/auditing/AuditedAuditorAware.java, src/integration/java/org/springframework/data/couchbase/repository/auditing/AuditedItem.java, src/integration/java/org/springframework/data/couchbase/repository/auditing/AuditedRepository.java, src/integration/java/org/springframework/data/couchbase/repository/auditing/AuditingTests.java, src/main/asciidoc/entity.adoc, src/main/java/org/springframework/data/couchbase/config/BeanNames.java, src/main/java/org/springframework/data/couchbase/core/mapping/event/AuditingEventListener.java, src/main/java/org/springframework/data/couchbase/repository/auditing/CouchbaseAuditingRegistrar.java, src/main/java/org/springframework/data/couchbase/repository/auditing/EnableCouchbaseAuditing.java
This commit adds support for auditing via the use of the four annotations (CreatedBy, LastModifiedBy, CreationDate, LastModificationDate), enabled via the EnableCouchbaseAuditing annotation.
As couchbase entities MUST have an id, the only case where the creation event can be detected is when the entity has a Version annotated field.
Pinging @olivergierke @daschl for review :smile:
=> DATACOUCH-91 - Support auditing (via java config)

src/integration/java/org/springframework/data/couchbase/repository/cdi/CdiRepositoryTests.java, src/integration/java/org/springframework/data/couchbase/repository/cdi/CouchbaseClientProducer.java, src/integration/java/org/springframework/data/couchbase/repository/cdi/CouchbaseClusterInfoProducer.java, src/integration/java/org/springframework/data/couchbase/repository/cdi/CouchbaseOperationsProducer.java, src/integration/java/org/springframework/data/couchbase/repository/cdi/OtherQualifier.java, src/integration/java/org/springframework/data/couchbase/repository/cdi/PersonDB.java, src/integration/java/org/springframework/data/couchbase/repository/cdi/QualifiedPersonRepository.java, src/main/java/org/springframework/data/couchbase/repository/cdi/CouchbaseRepositoryExtension.java
Qualifiers are now stored in their original set instead of using the toString representation.
=> DATACOUCH-203 - Use Set to store qualifiers in CDI extension.

pom.xml, src/main/java/org/springframework/data/couchbase/config/CouchbaseEnvironmentNoShutdownProxy.java
DATACOUCH-225 - Minimal SDK 2.2.6 support.
org.springframework.data.couchbase.config.CouchbaseEnvironmentNoShutdownProxy is missing new methods required by updated interface com.couchbase.client.core.env.CoreEnvironment (SDK 2.2.4+). Adding new delegate methods resolves this immediate issue, with all tests passing (though the CouchbaseEnvironmentNoShutdownProxy class doesn't appear to be directly or indirectly tested).
Jonathan Edwards, s34gull@gmail.com
=> DATACOUCH 225 - Minimal SDK 2.2.6 support

src/main/java/org/springframework/data/couchbase/repository/support/IndexManager.java
This should avoid problems when the message changes on the server side
(like in Couchbase Server 4.5).
@daschl pretty simple change, might remove the message check altogether
but I'm waiting for a confirmation about the code from query team.
=> DATACOUCH-229 - Check N1QL error codes rather than message

src/main/java/org/springframework/data/couchbase/config/CouchbaseEnvironmentFactoryBean.java, src/test/java/org/springframework/data/couchbase/config/CouchbaseSingleEnvironmentParserTest.java, src/test/resources/configurations/couchbaseSingleEnv-bean.xml
Defining `<couchbase:env/>` in [XML configuration](http://docs.spring.io/spring-data/couchbase/docs/2.0.0.RELEASE/reference/html/#configuration-xml) was causing a double
instantiation of DefaultCoreEnvironment, with subsequent warning in
logs:
```
[main] WARN c.c.client.core.env.CoreEnvironment - More than 1 Couchbase
Environments found (2), this can have severe impact on performance and
stability. Reuse environments!
```
=> DATACOUCH-235 - Fixed multiple Couchbase environments.

pom.xml, src/integration/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryViewTests.java, src/integration/java/org/springframework/data/couchbase/repository/CustomUserRepository.java, src/integration/java/org/springframework/data/couchbase/repository/index/IndexedRepositoryTestListener.java, src/integration/java/org/springframework/data/couchbase/repository/index/IndexedRepositoryTests.java, src/main/java/org/springframework/data/couchbase/config/CouchbaseEnvironmentFactoryBean.java, src/main/java/org/springframework/data/couchbase/config/CouchbaseEnvironmentNoShutdownProxy.java, src/main/java/org/springframework/data/couchbase/config/CouchbaseEnvironmentParser.java, src/main/java/org/springframework/data/couchbase/repository/support/IndexManager.java, src/test/java/org/springframework/data/couchbase/config/CouchbaseEnvironmentParserTest.java, src/test/java/org/springframework/data/couchbase/repository/RepositoryIndexUsageTest.java, src/test/java/org/springframework/data/couchbase/repository/query/PartTreeN1qBasedQueryTest.java, src/test/resources/configurations/couchbaseEnv-bean.xml
Motivation
----------
Fix failing integration tests due to query pipelinging, class cast
exception. Fix unit tests.
Changes
-------
Updating to newer client fixes pipelining issue
Update to newer client changes
-----------------------------
The update removes query enabled and query port properties from couchbase
environment bean as the query engine has been fully integrated and adds some
new properties like memcached hashing strategy, ssl key store which are not
yet exposed in this patch. There will be a follow patch which does that.
Fix tests
---------
use a simple select use index query to verify index existence versus using
system:indexes which require admin credentials. Fix view test where the view
query returns a list. Add other misc small fixes in integration and unit
tests. …
=> Update to client 2.4.1 and fix tests

src/integration/java/org/springframework/data/couchbase/config/AbstractCouchbaseDataConfigurationTest.java, src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java, src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseDataConfiguration.java, src/main/java/org/springframework/data/couchbase/config/AbstractReactiveCouchbaseConfiguration.java, src/main/java/org/springframework/data/couchbase/config/AbstractReactiveCouchbaseDataConfiguration.java, src/main/java/org/springframework/data/couchbase/config/CouchbaseConfigurationSupport.java
Motivation
----------
AbstractCouchbaseDataConfiguration was removed and
AbstractCouchbaseConfiguration was made the only configuration support
which implemented CouchbaseConfigurer. This broke integration with
Spring boot as they used CouchbaseConfigurer to auto configure client
initialization properties.
Changes
-------
Bring back support for AbstractCouchbaseDataConfiguration which allows the use
of CouchbaseConfigurer. Also added a similar configuration support for reactive
data repositories. Common beans between reactive and blocking are implemented
in CouchbaseConfigurationSupport class. The existing tests in
AbstractCouchbaseDataConfigurationTest does test this scenario. However the
previous commit had also changed the test because of the unawareness of spring
boot integration. …
=> DATACOUCH-279 - AbstractCouchbaseDataConfiguration no longer exists

src/integration/java/org/springframework/data/couchbase/core/AsyncUtils.java, src/integration/java/org/springframework/data/couchbase/core/RxJavaCouchbaseTemplateTests.java, src/main/java/org/springframework/data/couchbase/core/RxJavaCouchbaseOperations.java, src/main/java/org/springframework/data/couchbase/core/RxJavaCouchbaseTemplate.java, src/test/java/org/springframework/data/couchbase/core/VersionedReactiveBeer.java
Currently, there is only one way to save an entity - upsert.
**RxJavaCouchbaseOperations** is missing important feature of Couchbase 2.x API - cas updates.
The idea is to provide a few methods, which will apply a function to existing/non-existing input document, and perform safe replace/insert.
=> DATACOUCH-287 - Add CAS operations to RxJavaCouchbaseOperations.

CODE_OF_CONDUCT.adoc, README.md, src/main/asciidoc/configuration.adoc, src/main/asciidoc/template.adoc, src/main/resources/license.txt, src/main/resources/org/springframework/data/couchbase/config/spring-couchbase-1.0.xsd, src/main/resources/org/springframework/data/couchbase/config/spring-couchbase-2.0.xsd
This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were switched to an https URL with a 2xx status. While the status was successful, your review is still recommended.
https://assets.spring.io/drupal/node/feed.xml ([https](https://assets.spring.io/drupal/node/feed.xml) result 200).
https://stackoverflow.com/questions/tagged/spring-data ([https](https://stackoverflow.com/questions/tagged/spring-data) result 200).
https://stackoverflow.com/questions/tagged/spring-data-couchbase ([https](https://stackoverflow.com/questions/tagged/spring-data-couchbase) result 200).
https://www.springframework.org/schema/beans/spring-beans.xsd …
=> URL Cleanup

src/test/java/org/springframework/data/couchbase/core/mapping/MappingCouchbaseConverterTests.java
Seems that LocalDateTime now has microseconds, so the comparison of the unconverted
and converted LocalDateTime will fail, since the conversion/mapping only retains
millisecond precision.
=> DATACOUCH-459: Fix test issue which only shows up in java 11

src/main/asciidoc/repository.adoc, src/main/java/org/springframework/data/couchbase/core/query/WithConsistency.java, src/main/java/org/springframework/data/couchbase/repository/query/AbstractN1qlBasedQuery.java, src/main/java/org/springframework/data/couchbase/repository/query/CouchbaseQueryMethod.java, src/main/java/org/springframework/data/couchbase/repository/query/ReactiveAbstractN1qlBasedQuery.java, src/test/java/org/springframework/data/couchbase/repository/PartyRepository.java, src/test/java/org/springframework/data/couchbase/repository/ReactiveUserRepository.java, src/test/java/org/springframework/data/couchbase/repository/query/AbstractN1qlBasedQueryTest.java, src/test/java/org/springframework/data/couchbase/repository/query/ReactiveAbstractN1qlBasedQueryTest.java
When using N1QL with spring data repositories, there is no way to set the scan consistency individually, only a global default could be set.
This adds a `@WithConsistency` annotation that allows you to set the scan consistency per query.
When building the query parameters in `AbstractN1qlBasedQuery` and `ReactiveAbstractN1qlBasedQuery` this annotation is evaluated, the current behavior (using the global default) is used as fallback in case no annotation was used.
Currently the added methods are duplicated in `AbstractN1qlBasedQuery` and `ReactiveAbstractN1qlBasedQuery` since they don't share a common interface. The same is true for `CouchbaseOperations` and `RxJavaCouchbaseOperations`. I could extract a common interface from each and provide a default implementation.
=> #DATACOUCH-206 set scan consistency on repository method

src/test/java/org/springframework/data/couchbase/repository/ReactivePlaceIntegrationTests.java
There was an integration test which wasn't named properly, and
so it was running with regular tests.  This left the container
around, and all subsequent integration tests failed.  Simple
fix.
=> DATACOUCH-475 Couchbase builds failing.

src/test/java/org/springframework/data/couchbase/CouchbaseWaitStrategy.java, src/test/java/org/springframework/data/couchbase/TestContainerResource.java
After updating the POM to not have a fixed testcontainers version, we
discovered the tests were failing with later versions of testcontainers.  It
seems that they updated how they did WaitStrategy, deprecating the old way, so
our WaitStrategy was not being called.  That means no setup was done to
the cluster (passwords, buckets, etc...).  Simple fix was to move to the
new interface.
=> DATACOUCH-479 - Fix issue with testcontainers usage.

src/main/java/org/springframework/data/couchbase/repository/query/PartTreeN1qlBasedQuery.java, src/test/java/org/springframework/data/couchbase/repository/N1qlCouchbaseRepositoryIntegrationTests.java, src/test/java/org/springframework/data/couchbase/repository/PartyRepository.java
Support for positional parameters necessitated caching them, however
that was not done in a threadsafe fashion.  ThreadLocal storage is
sufficient to take care of the issue.  Added test for it while at it.
=> DATACOUCH-484 - Thread safety issue using findBy.

src/main/java/org/springframework/data/couchbase/config/BeanNames.java, src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplate.java, src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplateSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveCouchbaseTemplate.java, src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java, src/main/java/org/springframework/data/couchbase/core/mapping/event/AfterConvertCallback.java, src/main/java/org/springframework/data/couchbase/core/mapping/event/AuditingEventListener.java, src/main/java/org/springframework/data/couchbase/core/mapping/event/BeforeConvertCallback.java, src/main/java/org/springframework/data/couchbase/repository/auditing/CouchbaseAuditingRegistrar.java, src/main/java/org/springframework/data/couchbase/repository/auditing/EnableCouchbaseAuditing.java, src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateKeyValueIntegrationTests.java, src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateQueryIntegrationTests.java, src/test/java/org/springframework/data/couchbase/core/CustomTypeKeyIntegrationTests.java, src/test/java/org/springframework/data/couchbase/domain/AbstractEntity.java, src/test/java/org/springframework/data/couchbase/domain/Config.java, src/test/java/org/springframework/data/couchbase/domain/NaiveAuditorAware.java, src/test/java/org/springframework/data/couchbase/domain/Person.java, src/test/java/org/springframework/data/couchbase/domain/User.java, src/test/java/org/springframework/data/couchbase/domain/UserRepository.java, src/test/java/org/springframework/data/couchbase/domain/time/AuditingDateTimeProvider.java, src/test/java/org/springframework/data/couchbase/domain/time/CurrentDateTimeService.java, src/test/java/org/springframework/data/couchbase/domain/time/DateTimeService.java, src/test/java/org/springframework/data/couchbase/domain/time/FixedDateTimeService.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryKeyValueIntegrationTests.java
This reinstates the auditing that was present before the major
refactoring. Additional testing for createdBy, createdDate,
lastModifiedBy, lastModifiedDate has been added as well.
=> DATACOUCH-519 - Reinstate template auditing

src/main/java/org/springframework/data/couchbase/core/ReactiveFindByQueryOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveRemoveByQueryOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/query/Query.java, src/main/java/org/springframework/data/couchbase/core/query/StringQuery.java, src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateQueryIntegrationTests.java, src/test/java/org/springframework/data/couchbase/repository/query/StringN1qlQueryCreatorMockedTests.java, src/test/java/org/springframework/data/couchbase/repository/query/StringN1qlQueryCreatorTests.java
Use provided query instead of hardcoded statement.
=> DATACOUCH-615 Use query in removeByQuery

src/main/java/org/springframework/data/couchbase/core/query/QueryCriteria.java, src/main/java/org/springframework/data/couchbase/repository/query/N1qlQueryCreator.java, src/test/java/org/springframework/data/couchbase/domain/PersonRepository.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java
The complete property path was being quoted instead of the individual
components.  ie.  `address.street` instead of `address`.`street`
Also fixed another issue - changed the maybeQuote() method for
property names to correctly look for back-tics instead of double
quotes and changed the name accordingly.
=> DATACOUCH-583 - Nested properties in queries not working.

src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateQueryIntegrationTests.java
Verify that findByQuery works as expected (fixed as part of DATACOUCH-603)
=> DATACOUCH-619 FindByMatchingQuery integration test

src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplateSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveInsertByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveUpsertByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java, src/test/java/org/springframework/data/couchbase/domain/ComparableEntity.java, src/test/java/org/springframework/data/couchbase/domain/Course.java, src/test/java/org/springframework/data/couchbase/domain/PersonValue.java, src/test/java/org/springframework/data/couchbase/domain/PersonValueRepository.java, src/test/java/org/springframework/data/couchbase/domain/Submission.java, src/test/java/org/springframework/data/couchbase/domain/UserSubmission.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryKeyValueIntegrationTests.java
Modified applyUpdatedCas() to return accessor.getBean() which will
occur if the version property is Immutable.
Created applyUpdateId() that is analogous to applyUpdatedCas()
Factored out the equals() method that was used by a number of
test entity objects.
=> DATACOUCH-625 - Save doesn't return updated entity if immutable.

src/main/asciidoc/configuration.adoc
The format has changed as well. The release versions no longer have
the .RELEASE suffix - they are just the version number (i.e. 4.1.1)
And the snapshot versions have the suffix -SNAPSHOT (i.e. 4.2.0-SNAPSHOT)
instead of 4.1.0.BUILD-SNAPSHOT
=> DATACOUCH-653 - Update example versions in documentation.

src/test/java/org/springframework/data/couchbase/domain/Airport.java, src/test/java/org/springframework/data/couchbase/repository/ReactiveCouchbaseRepositoryQueryIntegrationTests.java
The problems were in the tests themselves.  The changes in datacouch-650 are fine.
These only run with "mvn integration-test", so the failures were not being caught.
=> DATACOUCH-661 - Fix integrations tests from 650

src/main/java/org/springframework/data/couchbase/core/ExecutableReplaceByIdOperation.java, src/main/java/org/springframework/data/couchbase/core/ExecutableReplaceByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveReplaceByIdOperation.java, src/main/java/org/springframework/data/couchbase/core/ReactiveReplaceByIdOperationSupport.java, src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateKeyValueIntegrationTests.java
This is identical to the change for 4.0.x and 4.1.x
=> DATACOUCH-630 - Add expiry to replace 4.2.x

src/main/java/org/springframework/data/couchbase/core/ExecutableReplaceByIdOperation.java, src/main/java/org/springframework/data/couchbase/core/ExecutableReplaceByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveReplaceByIdOperation.java, src/main/java/org/springframework/data/couchbase/core/ReactiveReplaceByIdOperationSupport.java, src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateKeyValueIntegrationTests.java
This is identical to the same change in 4.0.x
=> DATACOUCH-630 - Add expiry to replace 4.1.x.

src/main/java/org/springframework/data/couchbase/core/ExecutableReplaceByIdOperation.java, src/main/java/org/springframework/data/couchbase/core/ExecutableReplaceByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveReplaceByIdOperation.java, src/main/java/org/springframework/data/couchbase/core/ReactiveReplaceByIdOperationSupport.java, src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateKeyValueIntegrationTests.java
Add expiry option to 'replace' similar to how it is on 'insert' and 'update'
=> DATACOUCH-630 Add expiry option to replace.

src/main/java/org/springframework/data/couchbase/core/ExecutableInsertByIdOperation.java, src/main/java/org/springframework/data/couchbase/core/ExecutableRemoveByIdOperation.java, src/main/java/org/springframework/data/couchbase/core/ExecutableReplaceByIdOperation.java, src/main/java/org/springframework/data/couchbase/core/ExecutableUpsertByIdOperation.java, src/main/java/org/springframework/data/couchbase/core/InCollection.java, src/main/java/org/springframework/data/couchbase/core/OneAndAll.java, src/main/java/org/springframework/data/couchbase/core/OneAndAllReactive.java, src/main/java/org/springframework/data/couchbase/core/ReactiveInsertByIdOperation.java, src/main/java/org/springframework/data/couchbase/core/ReactiveRemoveByIdOperation.java, src/main/java/org/springframework/data/couchbase/core/ReactiveReplaceByIdOperation.java, src/main/java/org/springframework/data/couchbase/core/ReactiveUpsertByIdOperation.java, src/main/java/org/springframework/data/couchbase/core/WithDurability.java, src/main/java/org/springframework/data/couchbase/core/WithExpiry.java, src/test/java/org/springframework/data/couchbase/domain/UserAnnotated2.java
This is the same as the earlier DATACOUCH-645, but with the expiryExpression bug-fix and tests removed.
Added interfaces for apis on core objects which are common among
many objects. For instance withExpiry and withExpiryAnnotation on all the
insert/replace/upsert/remove objects.  The definition of an interface
simplifies testing of all the possible combinations - instead of having
four (or eight, counting Reactive), there is one interface to test
them all.
- [-] You submit test cases (unit or integration tests) that back your changes.
=> DATACOUCH-675 - Factor out interfaces for common methods.

src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplate.java, src/main/java/org/springframework/data/couchbase/core/index/CouchbasePersistentEntityIndexCreator.java, src/main/java/org/springframework/data/couchbase/core/mapping/CouchbaseMappingContext.java
This needs some discussion as to whether or not we want to support this.
I created the branch to capture the debugging and changes I had made
earlier when Denis asked me to investigate this issue.
Mark Paluch has indicated this is maybe not a good idea.
Due to the interdependencies of beans, autoindexing does not work
in the startup of a normal spring-boot application. Processing of
entities occurs during the initialization of CouchbaseMappinContext,
which occurs before initialization of MappingCouchbaseConverter,
which occurs before the initialization of CouchbaseTemplate -
which creates the indexCreator listener. So when the
AbstractMappingContext (CouchbaseMappingContext) is publishing
MappingContextEvents - there is not yet any indexCreator.
And subsequent processing of entities finds …
=> Datacouch 550 autoindex not working in spring boot app

src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplate.java, src/main/java/org/springframework/data/couchbase/core/index/CouchbasePersistentEntityIndexCreator.java, src/main/java/org/springframework/data/couchbase/core/mapping/CouchbaseMappingContext.java
Due to the interdependencies of beans, autoindexing does not work
in the startup of a normal spring-boot application. Processing of
entities occurs during the initialization of CouchbaseMappinContext,
which occurs before initialization of MappingCouchbaseConverter,
which occurs before the initialization of CouchbaseTemplate -
which creates the indexCreator listener. So when the
AbstractMappingContext (CouchbaseMappingContext) is publishing
MappingContextEvents - there is not yet any indexCreator.
And subsequent processing of entities finds the entities cached,
and therefore does not publish MappingContextEvents. This change
overrides the addPersistentEntity() and getPersistentEntity()
methods of AbstractMappingContext such that caching does not
preven the MappingContextEvents from being …
=> DATACOUCH-550 - Autoindexing does not work spring-boot application.

src/main/java/org/springframework/data/couchbase/core/ExecutableInsertByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ExecutableReplaceByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ExecutableUpsertByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveInsertByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveReplaceByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveUpsertByIdOperationSupport.java, src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateKeyValueIntegrationTests.java, src/test/java/org/springframework/data/couchbase/domain/UserAnnotated3.java
Support document expiryExpression and make the initial expiry
to be null instead of Zero in the fluent API. This allows
a client to 'unset' the expiry from an annotation by explcitly
setting withExpiry(Zero).
=> DATACOUCH-645 - Support document expiryExpression.

pom.xml, src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java, src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplate.java, src/main/java/org/springframework/data/couchbase/core/index/CouchbasePersistentEntityIndexCreator.java, src/main/java/org/springframework/data/couchbase/core/index/CouchbasePersistentEntityIndexResolver.java, src/main/java/org/springframework/data/couchbase/core/index/QueryIndexResolver.java, src/main/java/org/springframework/data/couchbase/core/mapping/CouchbaseMappingContext.java
pom.xml
- updated CouchbaseMock dependency to the official release on maven central, which now includes the required commit.
CouchbaseTemplate.java
- remove creation of CouchbasePersistentEntityIndexCreator
- there can only be a single CouchbaseMappingContext and CouchbasePersistentEntityIndexCreator, not sure why there was code dealing with multiples of each, and there was no corresponding tests for these assumptions.
- no longer does the job of a @Configuation class by gluing beans together with their dependencies.
CouchbaseMappingContext.java
- removed references to auto index creation, that functionality should be a completely separate concern.
CouchbasePersistentEntityIndexCreator.java
- as well as implementing ApplicationListener, it now also implements InitializingBean
- when …
=> DATACOUCH-550 - Refactored the usage of CouchbasePersistentEntityIndexCreator

src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java, src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplate.java, src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplateSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveCouchbaseTemplate.java, src/test/java/org/springframework/data/couchbase/domain/Config.java
[DATACOUCH-652](https://jira.spring.io/projects/DATACOUCH/issues/DATACOUCH-652)
TranslationService is defined as bean but in CouchbaseTemplateSupport. 
That bean is not being used and a new instance of JacksonTranslationSerivce is being created in the constructor.
We want CouchbaseTemplateSupport to receive a TranslationService type bean.
=> DATACOUCH-652 - Inject translation service bean in CouchbaseTemplateSupport.

src/main/java/org/springframework/data/couchbase/core/ExecutableRemoveByIdOperation.java, src/main/java/org/springframework/data/couchbase/core/ExecutableRemoveByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveRemoveByIdOperation.java, src/main/java/org/springframework/data/couchbase/core/ReactiveRemoveByIdOperationSupport.java, src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateKeyValueIntegrationTests.java
Add withCas() method to RemoveById as the cas in the entity cannot be used as the entity is not pass in the API.  The other option was to add methods like one(T entity) and all(Collection<T>), but those class with one(String id) and all(Collection<String> ids).
=> DATACOUCH-1041 - Add withCas() method to RemoveById.

src/main/java/org/springframework/data/couchbase/core/query/QueryCriteria.java, src/main/java/org/springframework/data/couchbase/repository/query/N1qlCountQueryCreator.java, src/main/java/org/springframework/data/couchbase/repository/query/N1qlQueryCreator.java, src/main/java/org/springframework/data/couchbase/repository/query/N1qlRepositoryQueryExecutor.java, src/main/java/org/springframework/data/couchbase/repository/query/PartTreeCouchbaseQuery.java, src/main/java/org/springframework/data/couchbase/repository/query/ReactivePartTreeCouchbaseQuery.java, src/main/java/org/springframework/data/couchbase/repository/query/ReactiveStringBasedCouchbaseQuery.java, src/main/java/org/springframework/data/couchbase/repository/query/StringN1qlQueryCreator.java, src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateQueryIntegrationTests.java, src/test/java/org/springframework/data/couchbase/core/query/QueryCriteriaTests.java, src/test/java/org/springframework/data/couchbase/domain/UserRepository.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java, src/test/java/org/springframework/data/couchbase/repository/query/N1qlQueryCreatorTests.java
This is a merge of mmonti's changeset into master. The changeset was made
on top of 4.1.x instead of master so it has a little catching up to do.
Closes #1066
=> DATACOUCH-1066 - Make QueryCriteria key a N1qlExpression.

src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplate.java, src/test/java/org/springframework/data/couchbase/core/CustomTypeKeyIntegrationTests.java
This reverts commit 80bae4bf67c8deb78fa9cef5c685335b62f16efd.
=> DATACOUCH-550 - Revert Refactored CouchbasePersistentEntityIndexCreator.

pom.xml, src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java, src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplate.java, src/main/java/org/springframework/data/couchbase/core/index/CouchbasePersistentEntityIndexCreator.java, src/main/java/org/springframework/data/couchbase/core/index/CouchbasePersistentEntityIndexResolver.java, src/main/java/org/springframework/data/couchbase/core/index/QueryIndexResolver.java, src/main/java/org/springframework/data/couchbase/core/mapping/CouchbaseMappingContext.java
=> DATACOUCH-550 - 41x revert index creator refactoring.

pom.xml
Revert Couchbase SDK to 3.0.1 on 4.1.x.
Closes #1103.
Original pull request #1107.
=> Revert Couchbase SDK to 3.0.1 on 4.1.x.

src/main/java/org/springframework/data/couchbase/repository/support/SimpleReactiveCouchbaseRepository.java, src/test/java/org/springframework/data/couchbase/domain/ReactiveAirportRepository.java, src/test/java/org/springframework/data/couchbase/repository/ReactiveCouchbaseRepositoryQueryIntegrationTests.java
It was present on non-Reactive, but missing from reactive.
Closes #1096.
Original pull request #1108.
=> Use queryScanConsistency on reactive deleteAll().

src/main/java/org/springframework/data/couchbase/core/query/QueryCriteria.java, src/test/java/org/springframework/data/couchbase/core/query/QueryCriteriaTests.java
Add QueryCriteria arrayContaining which maps to n1ql array_containing.
Closes #1073.
Original pull request #1109.
=> Add QueryCriteria arrayContaining.

src/main/java/org/springframework/data/couchbase/core/convert/AbstractCouchbaseConverter.java, src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java, src/test/java/org/springframework/data/couchbase/domain/AirportRepository.java, src/test/java/org/springframework/data/couchbase/domain/Iata.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java
Support enum in AbstractCouchbaseConverter.convertForWriteIfNeeded()
and also call that from
MappingCouchbaseConverter.getPotentiallyConvertedSimpleWrite()
Closes #1069.
Original pull request #1112.
=> Support enum arguments on repository queries.

src/main/java/org/springframework/data/couchbase/core/query/N1QLExpression.java, src/test/java/org/springframework/data/couchbase/core/query/QueryCriteriaTests.java
Fix syntax for USE KEYS [ ... ]
Closes #1064.
Original pull request: #1113.
=> Fix N1qlExpression keys.

src/main/java/org/springframework/data/couchbase/core/convert/DefaultCouchbaseTypeMapper.java, src/main/java/org/springframework/data/couchbase/core/convert/TypeAwareTypeInformationMapper.java, src/main/java/org/springframework/data/couchbase/repository/query/StringN1qlQueryCreator.java, src/test/java/org/springframework/data/couchbase/domain/Airport.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java
DefaultCouchbaseTypeMapper uses TypeAlias annotation if present.
Test case also uncovered that TypeAlias was being ignored for
string queries.
Closes #1119.
=> DefaultCouchbaseTypeMapper uses TypeAlias annotation if present.

src/main/java/org/springframework/data/couchbase/core/ReactiveRemoveByQueryOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/query/Query.java, src/main/java/org/springframework/data/couchbase/core/query/StringQuery.java, src/test/java/org/springframework/data/couchbase/domain/Airport.java, src/test/java/org/springframework/data/couchbase/domain/AirportRepository.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java
=> Add override of toN1qlRemoveString() to StringQuery.

src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java, src/test/java/org/springframework/data/couchbase/repository/ReactiveCouchbaseRepositoryKeyValueIntegrationTests.java
Expose ObjectMapper used by JsonSerializer
Closes #1130.
=> Expose ObjectMapper used by JsonSerializer

src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java, src/main/java/org/springframework/data/couchbase/core/convert/AbstractCouchbaseConverter.java, src/main/java/org/springframework/data/couchbase/repository/query/StringBasedN1qlQueryParser.java, src/test/java/org/springframework/data/couchbase/domain/Config.java
1) change examples in Config to show creating repository mappings using
existing MappingCouchbaseConverter (which have customConversions /
BeanNames.COUCHBASE_CUSTOM_CONVERSIONS and applicationContext)
instead of creating their own and then adding the customConversion and
applicationContext.
2) remove unused members fro StringBasedN1qlQueryParser
Closes #1141.
=> Improve framework for custom mapping couchbase converter.

src/main/java/org/springframework/data/couchbase/repository/support/CrudMethodMetadataPostProcessor.java, src/test/java/org/springframework/data/couchbase/domain/UserColRepository.java, src/test/java/org/springframework/data/couchbase/repository/query/CouchbaseRepositoryQueryCollectionIntegrationTests.java
Omit annotations from the repository and domaintype in
CrudMethodMetadata as they may be different for the same method.
The annotations from the repository and domaintype are obtained directly
in CouchbaseRepositoryBase.
Closes #1168.
=> Omit annotations from the repository and domaintype in CrudMethodMetadata.

src/main/java/org/springframework/data/couchbase/core/index/CouchbasePersistentEntityIndexCreator.java, src/main/java/org/springframework/data/couchbase/core/index/CouchbasePersistentEntityIndexResolver.java, src/test/java/org/springframework/data/couchbase/domain/Airline.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryAutoQueryIndexIntegrationTests.java
=> Handle auto index on field path.

src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java
Only scan Document annotated classes.
Closes #1121.
=> Do not scan Persistent annotated classes.

src/main/java/org/springframework/data/couchbase/repository/query/N1qlQueryCreator.java, src/main/java/org/springframework/data/couchbase/repository/query/StringBasedN1qlQueryParser.java, src/test/java/org/springframework/data/couchbase/domain/Airport.java, src/test/java/org/springframework/data/couchbase/domain/User.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java
Expiration annotation on field will retrieve expiration in N1ql queries. Previously the annotation only allowed it to be used in a predicate.
Also consolidates META() substitution in N1qlQueryCreator and StringBasedN1qQueryParser.
Closes #1060.
=> Expiration annotation on field will retrieve expiration in N1ql queries.

src/main/java/org/springframework/data/couchbase/core/mapping/BasicCouchbasePersistentProperty.java, src/test/java/org/springframework/data/couchbase/domain/Person.java, src/test/java/org/springframework/data/couchbase/domain/PersonRepository.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java
=> Field(name=foo) annotation work like Field(foo) and Field(value=foo).

src/main/java/org/springframework/data/couchbase/repository/query/StringBasedN1qlQueryParser.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java
Project getFieldName() instead of getName() since getFieldName() is what is stored in the document.
The decoder handles populating getName() entity property with the getFieldName() json property.
Closes #1184.
=> N1ql query should project getFieldName() instead of getName().

src/main/asciidoc/configuration.adoc
The urls in the example are ok, but when the hot link in the
text is clicked on, it redirects to a 404. This fixes the hot links.
Closes #1177.
=> Fix links to snapshot and milestone in doc.

src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplateSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveCouchbaseTemplateSupport.java
=> Log exceptions thrown from events.

src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateKeyValueIntegrationTests.java, src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateQueryCollectionIntegrationTests.java, src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateQueryIntegrationTests.java, src/test/java/org/springframework/data/couchbase/core/ReactiveCouchbaseTemplateKeyValueIntegrationTests.java, src/test/java/org/springframework/data/couchbase/core/query/ReactiveCouchbaseTemplateQueryCollectionIntegrationTests.java, src/test/java/org/springframework/data/couchbase/domain/Config.java, src/test/java/org/springframework/data/couchbase/domain/NaiveAuditorAware.java, src/test/java/org/springframework/data/couchbase/domain/User.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java, src/test/java/org/springframework/data/couchbase/repository/ReactiveCouchbaseRepositoryKeyValueIntegrationTests.java
Remove unnecessary auditorAwareRef from test config as it causes
confusion. The property does not need to be preset for the auditorAwareRef
bean to be used.
The dateTimeProviderRef must be present for the provided
dateTimeProviderRef bean to be used.
Fixed up the test cases so they no longer work by accident.
Closes #1052.
=> Remove unnecessary auditorAwareRef from test config.

src/main/java/org/springframework/data/couchbase/core/ExecutableFindByQueryOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveFindByQueryOperationSupport.java, src/test/java/org/springframework/data/couchbase/domain/AirportRepository.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java
Also just use the first projected property instead of one explicitly named "count".
Closes #925,#960.
=> Throw an explicit exception if count query does not return a count.

src/main/java/org/springframework/data/couchbase/core/query/Query.java, src/main/java/org/springframework/data/couchbase/repository/query/CouchbaseQueryExecution.java, src/main/java/org/springframework/data/couchbase/repository/query/N1qlQueryCreator.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java
Also creates the query with skip and limit from any Pageable parameter instead of applying it later.
Closes #1191.
=> Remove the sort from query before executing count.

src/main/java/org/springframework/data/couchbase/core/query/Query.java, src/main/java/org/springframework/data/couchbase/core/query/StringQuery.java, src/main/java/org/springframework/data/couchbase/repository/query/StringBasedN1qlQueryParser.java, src/main/java/org/springframework/data/couchbase/repository/query/StringN1qlQueryCreator.java, src/test/java/org/springframework/data/couchbase/domain/AirportRepository.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java
=> Fix ArrayIndexOutOfBoundsException on String queries that use paging.

src/main/java/org/springframework/data/couchbase/core/ReactiveFindByQueryOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/query/Query.java, src/main/java/org/springframework/data/couchbase/repository/query/CouchbasePartTree.java, src/main/java/org/springframework/data/couchbase/repository/query/N1qlQueryCreator.java, src/main/java/org/springframework/data/couchbase/repository/query/PartTreeCouchbaseQuery.java, src/test/java/org/springframework/data/couchbase/domain/AirportRepository.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java
=> Support derived queries from methods named findDistinctF1AndF2ByF3()

src/main/java/org/springframework/data/couchbase/core/ExecutableFindByQueryOperation.java, src/main/java/org/springframework/data/couchbase/core/ExecutableFindByQueryOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveFindByQueryOperation.java, src/main/java/org/springframework/data/couchbase/core/ReactiveFindByQueryOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/query/Query.java, src/main/java/org/springframework/data/couchbase/core/query/StringQuery.java, src/main/java/org/springframework/data/couchbase/core/support/WithProjecting.java, src/main/java/org/springframework/data/couchbase/repository/query/AbstractCouchbaseQuery.java, src/main/java/org/springframework/data/couchbase/repository/query/AbstractReactiveCouchbaseQuery.java, src/main/java/org/springframework/data/couchbase/repository/query/CouchbaseQueryExecution.java, src/main/java/org/springframework/data/couchbase/repository/query/N1qlRepositoryQueryExecutor.java, src/main/java/org/springframework/data/couchbase/repository/query/ReactiveCouchbaseQueryExecution.java, src/main/java/org/springframework/data/couchbase/repository/query/StringBasedN1qlQueryParser.java, src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateKeyValueIntegrationTests.java, src/test/java/org/springframework/data/couchbase/domain/AirportMini.java, src/test/java/org/springframework/data/couchbase/domain/AirportRepository.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java
=> Add project(fields) to findByQuery similar to same method on findById.

src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java, src/test/java/org/springframework/data/couchbase/util/ClusterAwareIntegrationTests.java
Also rearranges test initializations so test order doesn't matter.
Closes #1221.
=> Pass source as parent when reading subobject.

src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java, src/main/java/org/springframework/data/couchbase/core/mapping/BasicCouchbasePersistentEntity.java, src/main/java/org/springframework/data/couchbase/core/mapping/CouchbasePersistentEntity.java, src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateKeyValueIntegrationTests.java, src/test/java/org/springframework/data/couchbase/core/ReactiveCouchbaseTemplateKeyValueIntegrationTests.java, src/test/java/org/springframework/data/couchbase/core/mapping/BasicCouchbasePersistentEntityTests.java, src/test/java/org/springframework/data/couchbase/repository/query/StringN1qlQueryCreatorTests.java
Also adds test for exceptions thrown during events - with validator.
Closes #1204.
=> Use expiry(duration) with duration.

pom.xml, src/test/java/org/springframework/data/couchbase/domain/Airport.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java
=> Test case for exceptions thrown from events - validation.

src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java, src/main/java/org/springframework/data/couchbase/core/CouchbaseOperations.java, src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplate.java, src/main/java/org/springframework/data/couchbase/core/ReactiveCouchbaseOperations.java, src/main/java/org/springframework/data/couchbase/core/ReactiveCouchbaseTemplate.java, src/main/java/org/springframework/data/couchbase/core/ReactiveFindByQueryOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveRemoveByQueryOperationSupport.java, src/test/java/org/springframework/data/couchbase/domain/AirportRepository.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java
This is chiefly to allow all queries to have scanConsistency REQUEST_PLUS to accommodate tests which insert and then query.  In a production setting, the default consistency should be left null.
In 4.3, the @ScanConsistency annotation can be applied to entity classes to have the same effect.
Closes #1243.
=> Reinstate the getDefaultConsistency() method in the Configuration.

src/main/java/org/springframework/data/couchbase/core/query/StringQuery.java, src/main/java/org/springframework/data/couchbase/repository/query/N1qlQueryCreator.java, src/main/java/org/springframework/data/couchbase/repository/query/StringBasedN1qlQueryParser.java, src/test/java/org/springframework/data/couchbase/domain/Airport.java, src/test/java/org/springframework/data/couchbase/domain/AirportRepository.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java
=> Backport fix for Pageable in String Query.

src/main/java/org/springframework/data/couchbase/core/query/QueryCriteria.java, src/test/java/org/springframework/data/couchbase/domain/AirportRepository.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java
=> Handle Collection<> parameters to repository query methods.

src/main/java/org/springframework/data/couchbase/core/mapping/event/ValidatingCouchbaseEventListener.java
=> Fix for 5_0_x branch.

src/main/java/org/springframework/data/couchbase/core/mapping/CouchbaseDocument.java
=> Fix remaining javadoc in 5.0.x

src/main/asciidoc/collections.adoc, src/main/asciidoc/index.adoc
=> Add Collections to Reference Documentation.

src/main/java/org/springframework/data/couchbase/cache/CouchbaseCache.java, src/test/java/org/springframework/data/couchbase/cache/CacheUser.java, src/test/java/org/springframework/data/couchbase/cache/CouchbaseCacheIntegrationTests.java
Use toStoreValue(value) to substitute null objects with NullValue.INSTANCE when putting.  fromStoreValue(value) does the opposite when getting.
Closes #939.
=> Allow caching null objects.

src/main/java/org/springframework/data/couchbase/repository/query/StringBasedN1qlQueryParser.java, src/test/java/org/springframework/data/couchbase/domain/AbstractUser.java, src/test/java/org/springframework/data/couchbase/domain/AbstractUserRepository.java, src/test/java/org/springframework/data/couchbase/domain/Airport.java, src/test/java/org/springframework/data/couchbase/domain/AirportRepository.java, src/test/java/org/springframework/data/couchbase/domain/OtherUser.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseAbstractRepositoryIntegrationTests.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java, src/test/java/org/springframework/data/couchbase/repository/query/StringN1qlQueryCreatorMockedTests.java
Restore projection of class in queries. This is necessary for abstract repositories.
Closes #1315.
=> Restore projection of class.

src/main/java/org/springframework/data/couchbase/repository/query/AbstractCouchbaseQuery.java, src/main/java/org/springframework/data/couchbase/repository/query/CouchbaseQueryExecution.java, src/main/java/org/springframework/data/couchbase/repository/query/StringBasedN1qlQueryParser.java, src/test/java/org/springframework/data/couchbase/domain/AirportRepository.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java
Fix slice support. Also discontinue use of deprecated class.
Closes #1323.
=> Fix slice support.

src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplateSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveCouchbaseTemplateSupport.java, src/main/java/org/springframework/data/couchbase/core/mapping/CouchbaseDocument.java, src/main/java/org/springframework/data/couchbase/core/mapping/CouchbaseList.java, src/main/java/org/springframework/data/couchbase/repository/auditing/CouchbaseAuditingRegistrar.java, src/main/java/org/springframework/data/couchbase/repository/query/support/N1qlUtils.java, src/main/java/org/springframework/data/couchbase/repository/support/ViewPostProcessor.java, src/test/java/org/springframework/data/couchbase/util/ClusterInvocationProvider.java, src/test/java/org/springframework/data/couchbase/util/TestClusterConfig.java, src/test/java/org/springframework/data/couchbase/util/Util.java
=> Javadoc and other java 1_8 compatible changes in 50x back to main.

src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateKeyValueIntegrationTests.java, src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateQueryCollectionIntegrationTests.java, src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateQueryIntegrationTests.java, src/test/java/org/springframework/data/couchbase/core/CustomTypeKeyIntegrationTests.java, src/test/java/org/springframework/data/couchbase/core/ReactiveCouchbaseTemplateKeyValueIntegrationTests.java, src/test/java/org/springframework/data/couchbase/core/query/ReactiveCouchbaseTemplateQueryCollectionIntegrationTests.java, src/test/java/org/springframework/data/couchbase/domain/FluxTest.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryKeyValueIntegrationTests.java, src/test/java/org/springframework/data/couchbase/repository/ReactiveCouchbaseRepositoryKeyValueIntegrationTests.java
=> Have tests remove the documents they insert.

src/main/java/org/springframework/data/couchbase/repository/support/SimpleCouchbaseRepository.java, src/main/java/org/springframework/data/couchbase/repository/support/SimpleReactiveCouchbaseRepository.java, src/test/java/org/springframework/data/couchbase/domain/ReactiveAirlineRepository.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryKeyValueIntegrationTests.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java, src/test/java/org/springframework/data/couchbase/repository/ReactiveCouchbaseRepositoryKeyValueIntegrationTests.java, src/test/java/org/springframework/data/couchbase/repository/ReactiveCouchbaseRepositoryQueryIntegrationTests.java
=> Add mechanism for save to do one of insert, replace or upsert.

src/main/asciidoc/entity.adoc, src/main/java/org/springframework/data/couchbase/core/CouchbaseExceptionTranslator.java, src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateKeyValueIntegrationTests.java, src/test/java/org/springframework/data/couchbase/core/ReactiveCouchbaseTemplateKeyValueIntegrationTests.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryKeyValueIntegrationTests.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java, src/test/java/org/springframework/data/couchbase/repository/ReactiveCouchbaseRepositoryKeyValueIntegrationTests.java, src/test/java/org/springframework/data/couchbase/repository/ReactiveCouchbaseRepositoryQueryIntegrationTests.java
Translate CasMismatchException to OptimisticLockingFailureException
instead of DataIntegrityViolationException.  CasMismatchException is
a ConcurrencyFailureException which is a TransientDataAccessException.
Versus DataIntegrityViolation, which is a NonTransientDataAccessException.
Closes #1339.
=> Translate CasMismatchException to OptimisticLockingFailureException.

src/main/java/org/springframework/data/couchbase/cache/CouchbaseCacheConfiguration.java, src/test/java/org/springframework/data/couchbase/cache/CouchbaseCacheCollectionIntegrationTests.java
=> Allow CouchbaseCacheConfiguration to set collection.

src/main/java/org/springframework/data/couchbase/repository/CouchbaseRepository.java, src/main/java/org/springframework/data/couchbase/repository/ReactiveCouchbaseRepository.java, src/test/java/org/springframework/data/couchbase/domain/AirlineRepository.java, src/test/java/org/springframework/data/couchbase/domain/LibraryRepository.java, src/test/java/org/springframework/data/couchbase/domain/ReactiveAirlineRepository.java, src/test/java/org/springframework/data/couchbase/domain/ReactiveUserRepository.java, src/test/java/org/springframework/data/couchbase/domain/SubscriptionTokenRepository.java, src/test/java/org/springframework/data/couchbase/domain/UserSubmissionAnnotatedRepository.java, src/test/java/org/springframework/data/couchbase/domain/UserSubmissionRepository.java, src/test/java/org/springframework/data/couchbase/domain/UserSubmissionUnannotatedRepository.java
=> Accomodate changes to springframework repository interfaces.

src/main/asciidoc/caching.adoc, src/main/asciidoc/index.adoc, src/test/java/org/springframework/data/couchbase/cache/CouchbaseCacheCollectionIntegrationTests.java, src/test/java/org/springframework/data/couchbase/cache/CouchbaseCacheIntegrationTests.java, src/test/java/org/springframework/data/couchbase/domain/Config.java, src/test/java/org/springframework/data/couchbase/domain/User.java, src/test/java/org/springframework/data/couchbase/domain/UserRepository.java
=> Reinstate CouchbaseCache documentation.

src/main/asciidoc/caching.adoc, src/test/java/org/springframework/data/couchbase/domain/Config.java
=> Fix update to cache documentation.

src/main/java/org/springframework/data/couchbase/cache/CouchbaseCache.java, src/main/java/org/springframework/data/couchbase/cache/CouchbaseCacheWriter.java, src/main/java/org/springframework/data/couchbase/cache/DefaultCouchbaseCacheWriter.java, src/test/java/org/springframework/data/couchbase/cache/CouchbaseCacheCollectionIntegrationTests.java
=> Fix cache.clear() to use collection.

src/main/java/org/springframework/data/couchbase/cache/DefaultCouchbaseCacheWriter.java, src/test/java/org/springframework/data/couchbase/cache/CouchbaseCacheIntegrationTests.java
=> Fix cache to use collections part 2.

pom.xml, src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateQueryCollectionIntegrationTests.java, src/test/java/org/springframework/data/couchbase/core/CustomTypeKeyIntegrationTests.java, src/test/java/org/springframework/data/couchbase/domain/CapellaConnectSample.java, src/test/java/org/springframework/data/couchbase/domain/Config.java, src/test/java/org/springframework/data/couchbase/domain/FluxTest.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseAbstractRepositoryIntegrationTests.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryAutoQueryIndexIntegrationTests.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryKeyValueIntegrationTests.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java, src/test/java/org/springframework/data/couchbase/repository/ReactiveCouchbaseRepositoryKeyValueIntegrationTests.java, src/test/java/org/springframework/data/couchbase/repository/ReactiveCouchbaseRepositoryQueryIntegrationTests.java, src/test/java/org/springframework/data/couchbase/repository/query/CouchbaseRepositoryQuerydslIntegrationTests.java, src/test/java/org/springframework/data/couchbase/repository/query/StringN1qlQueryCreatorMockedTests.java, src/test/java/org/springframework/data/couchbase/repository/query/StringN1qlQueryCreatorTests.java, src/test/java/org/springframework/data/couchbase/util/ClusterAwareIntegrationTests.java, src/test/java/org/springframework/data/couchbase/util/CollectionAwareIntegrationTests.java, src/test/java/org/springframework/data/couchbase/util/JavaIntegrationTests.java, src/test/java/org/springframework/data/couchbase/util/MockTestCluster.java, src/test/java/org/springframework/data/couchbase/util/TestClusterConfig.java, src/test/java/org/springframework/data/couchbase/util/UnmanagedTestCluster.java, src/test/resources/integration.properties
=> Support testing against Capella.

src/main/java/org/springframework/data/couchbase/repository/support/CrudMethodMetadataPostProcessor.java, src/main/java/org/springframework/data/couchbase/repository/support/SimpleReactiveCouchbaseRepository.java
Retrieve the data before any reactive lambda.
When the method returns, in can immediately be removed from
the currentInvocation, and the previous data restored.
Closes #1392.
=> Proper handling of metadata from CrudMethodMetadataPostProcessor.

src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplateSupport.java, src/main/java/org/springframework/data/couchbase/core/NonReactiveSupportWrapper.java, src/main/java/org/springframework/data/couchbase/core/ReactiveCouchbaseTemplateSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveFindByAnalyticsOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveFindByQueryOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveTemplateSupport.java, src/main/java/org/springframework/data/couchbase/core/TemplateSupport.java
=> Only throw exception for id and cas not projected if needed.

src/main/java/org/springframework/data/couchbase/cache/DefaultCouchbaseCacheWriter.java, src/test/java/org/springframework/data/couchbase/util/JavaIntegrationTests.java
Also fix test setup index flakiness on older servers.
Closes #1417.
=> Fix Collection Support for Cache for non-Collection Server.

src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplateSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveCouchbaseTemplateSupport.java, src/main/java/org/springframework/data/couchbase/repository/query/StringBasedN1qlQueryParser.java, src/test/java/org/springframework/data/couchbase/repository/query/StringN1qlQueryCreatorMockedTests.java
=> Only project id and cas if required.

pom.xml
It hangs/timesout frequently and does not appear to be needed.
Closes #1433.
=> Remove jitpack.io from repositories in pom.xml

src/main/java/org/springframework/data/couchbase/core/convert/OtherConverters.java, src/test/java/org/springframework/data/couchbase/core/mapping/MappingCouchbaseConverterTests.java
Add BigDecimal converter, add converter tests for BigDecimal and BigInteger.
Since BigDecimal is now supported, it cannot be used in the CustomerConverter tests.
So instead use ChoiceFormat for CustomConverter tests.
Closes #1459.
=> Add BigDecimal converter.

src/main/asciidoc/repository.adoc, src/main/java/org/springframework/data/couchbase/core/ReactiveFindByQueryOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveRemoveByQueryOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/convert/join/N1qlJoinResolver.java, src/main/java/org/springframework/data/couchbase/core/query/N1QLExpression.java, src/main/java/org/springframework/data/couchbase/core/query/N1QLQuery.java, src/main/java/org/springframework/data/couchbase/core/query/Query.java, src/main/java/org/springframework/data/couchbase/core/query/StringQuery.java, src/main/java/org/springframework/data/couchbase/repository/query/N1qlRepositoryQueryExecutor.java, src/main/java/org/springframework/data/couchbase/repository/query/ReactiveStringBasedCouchbaseQuery.java, src/main/java/org/springframework/data/couchbase/repository/query/StringBasedCouchbaseQuery.java, src/main/java/org/springframework/data/couchbase/repository/query/StringBasedN1qlQueryParser.java, src/main/java/org/springframework/data/couchbase/repository/query/StringN1qlQueryCreator.java, src/test/java/org/springframework/data/couchbase/domain/UserRepository.java, src/test/java/org/springframework/data/couchbase/repository/query/StringN1qlQueryCreatorIntegrationTests.java, src/test/java/org/springframework/data/couchbase/repository/query/StringN1qlQueryCreatorMockedTests.java
This adds n1ql.scope and n1ql.collection spel expressions for
@Query so that n1ql.bucket doesn't need to be overloaded with
the collection name. This will make the bucket name available
in n1q.bucket.
This is a breaking change as queries that used n1ql.bucket to
get the collection name (especially in the case of pre-scope-
and-collection @Queries that (a) referenced n1ql.bucket instead
of referencing other spel expressions that include the
bucket/collection name; and (b)  still worked after the
repository was moved from a bucket onto a collection by
virtue of n1ql.bucket having the value of the collection in
such instances.
Closes #1445.
=> Add n1ql.scope and n1ql.collection spel expressions for @Query.

src/main/java/org/springframework/data/couchbase/repository/query/StringBasedN1qlQueryParser.java
n1ql.bucket will continue to be (collection != null ? collection : bucket)
so that queries that referenced n1ql.bucket after being used on collections
will still work.
Closes #1462.
=> Back-out the breaking part of 1445 from 4_4_x.

src/main/java/org/springframework/data/couchbase/repository/query/AbstractCouchbaseQuery.java, src/main/java/org/springframework/data/couchbase/repository/query/AbstractReactiveCouchbaseQuery.java, src/main/java/org/springframework/data/couchbase/repository/query/CouchbaseQueryExecution.java, src/main/java/org/springframework/data/couchbase/repository/query/ReactiveCouchbaseQueryExecution.java, src/test/java/org/springframework/data/couchbase/domain/AirportRepository.java, src/test/java/org/springframework/data/couchbase/domain/AirportRepositoryAnnotated.java, src/test/java/org/springframework/data/couchbase/domain/FluxTest.java, src/test/java/org/springframework/data/couchbase/domain/ReactiveAirportRepository.java, src/test/java/org/springframework/data/couchbase/domain/ReactiveAirportRepositoryAnnotated.java, src/test/java/org/springframework/data/couchbase/repository/ReactiveCouchbaseRepositoryKeyValueIntegrationTests.java, src/test/java/org/springframework/data/couchbase/repository/ReactiveCouchbaseRepositoryQueryIntegrationTests.java, src/test/java/org/springframework/data/couchbase/repository/query/CouchbaseRepositoryQueryCollectionIntegrationTests.java, src/test/java/org/springframework/data/couchbase/repository/query/ReactiveCouchbaseRepositoryQueryCollectionIntegrationTests.java, src/test/java/org/springframework/data/couchbase/util/ClusterAwareIntegrationTests.java
This is a more localized change than the one in main.
Closes #1464.
=> Fix 1441 in 4_4_x - scope and collection not considered in repo delete.

src/main/java/org/springframework/data/couchbase/core/ReactiveFindByQueryOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveRemoveByQueryOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/convert/join/N1qlJoinResolver.java, src/main/java/org/springframework/data/couchbase/core/query/N1QLQuery.java, src/main/java/org/springframework/data/couchbase/core/query/Query.java, src/main/java/org/springframework/data/couchbase/core/query/StringQuery.java, src/test/java/org/springframework/data/couchbase/repository/query/StringN1qlQueryCreatorTests.java, src/test/java/org/springframework/data/couchbase/util/JavaIntegrationTests.java
=> Remove template dependency from string n1ql, also fix StringN1ql tests.

src/test/java/org/springframework/data/couchbase/domain/FluxIntegrationTests.java
=> Rename FluxTest to FluxIntegrationTests as it requires a server.

src/main/java/com/querydsl/couchbase/document/CouchbaseDocumentSerializer.java, src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java, src/main/java/org/springframework/data/couchbase/core/query/QueryCriteria.java, src/main/java/org/springframework/data/couchbase/repository/query/N1qlQueryCreator.java, src/test/java/org/springframework/data/couchbase/core/query/QueryCriteriaTests.java, src/test/java/org/springframework/data/couchbase/domain/UserRepository.java, src/test/java/org/springframework/data/couchbase/repository/query/CouchbaseRepositoryQuerydslIntegrationTests.java, src/test/java/org/springframework/data/couchbase/repository/query/N1qlQueryCreatorTests.java
=> Add support for ignoreCase in queries derived from method names.

pom.xml
The latest Reactor and Spring Data snapshots are currently incompatible due to some backwards incompatible changes in Reactor. This breaks both Spring Data Couchbase itself and the Couchbase Java client. This has gone unnoticed until now as the Spring Data Couchbase build is not using the version of Reactor that's specified in the Spring Data parent. This pull request corrects this.
Note that the changes in this PR will not build cleanly due to the aforementioned breaking changes.
/cc @simonbasle
/cc @mp911de
=> Use version from parent for all Reactor modules

src/main/java/org/springframework/data/couchbase/core/ReactiveInsertByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveRemoveByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveReplaceByIdOperationSupport.java, src/test/java/org/springframework/data/couchbase/transactions/CouchbaseTransactionalUnsettableParametersIntegrationTests.java
=> Reject withDurability(durabilityLevel) in transactions.

src/main/java/org/springframework/data/couchbase/core/ReactiveRemoveByIdOperation.java
=> Give args to oneEntity() and allEntities() relevant names.

src/test/java/org/springframework/data/couchbase/domain/CapellaConnectSample.java
=> Rely on SDK provided cert instead of insecure trust manager.

src/main/java/org/springframework/data/couchbase/core/CouchbaseOperations.java, src/main/java/org/springframework/data/couchbase/core/ReactiveCouchbaseOperations.java, src/main/java/org/springframework/data/couchbase/core/ReactiveCouchbaseTemplate.java
=> Add javadoc for save operations.

README.adoc, pom.xml, src/main/asciidoc/transactions.adoc, src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java, src/main/java/org/springframework/data/couchbase/config/BeanNames.java, src/test/java/org/springframework/data/couchbase/transactions/CouchbasePersonTransactionReactiveIntegrationTests.java, src/test/java/org/springframework/data/couchbase/transactions/CouchbaseTransactionalNonAllowableOperationsIntegrationTests.java, src/test/java/org/springframework/data/couchbase/transactions/CouchbaseTransactionalOptionsIntegrationTests.java, src/test/java/org/springframework/data/couchbase/transactions/CouchbaseTransactionalPropagationIntegrationTests.java, src/test/java/org/springframework/data/couchbase/transactions/CouchbaseTransactionalRepositoryIntegrationTests.java, src/test/java/org/springframework/data/couchbase/transactions/CouchbaseTransactionalTemplateIntegrationTests.java, src/test/java/org/springframework/data/couchbase/transactions/CouchbaseTransactionalUnsettableParametersIntegrationTests.java, src/test/java/org/springframework/data/couchbase/transactions/PersonService.java, src/test/java/org/springframework/data/couchbase/transactions/PersonServiceReactive.java, src/test/java/org/springframework/data/couchbase/transactions/ReactiveTransactionalTemplateIntegrationTests.java, src/test/java/org/springframework/data/couchbase/transactions/TransactionTemplateIntegrationTests.java, src/test/java/org/springframework/data/couchbase/transactions/sdk/SDKReactiveTransactionsNonAllowableOperationsIntegrationTests.java, src/test/java/org/springframework/data/couchbase/transactions/sdk/SDKReactiveTransactionsTemplateIntegrationTests.java, src/test/java/org/springframework/data/couchbase/transactions/sdk/SDKTransactionsNonAllowableOperationsIntegrationTests.java
Closes #1454.
Staged documentation is available at : https://mikereiche.github.io/staged/transactions.html
=> Update transactions documentation for native transaction support.

pom.xml, spring-data-couchbase/pom.xml, spring-data-testapp/pom.xml, spring-data-testapp/src/main/java/com/example/demo/Airport.java, spring-data-testapp/src/main/java/com/example/demo/AirportRepository.java, spring-data-testapp/src/main/java/com/example/demo/AirportService.java, spring-data-testapp/src/main/java/com/example/demo/CmdRunner.java, spring-data-testapp/src/main/java/com/example/demo/Config.java, spring-data-testapp/src/main/java/com/example/demo/DemoApplication.java, spring-data-testapp/src/main/java/com/example/demo/Iata.java, spring-data-testapp/src/main/resources/application.properties, spring-data-testapp/src/test/java/com/example/demo/DemoApplicationTests.java
=> Tidy testapp and poms.

spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/TransactionalSupport.java, spring-data-couchbase/src/main/java/org/springframework/data/couchbase/transaction/CouchbaseCallbackTransactionManager.java
=> Fix call to block() in CouchbaseCallbackTransactionManager.

spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/AbstractTemplateSupport.java, spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplateSupport.java, spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/NonReactiveSupportWrapper.java, spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/ReactiveCouchbaseTemplateSupport.java, spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/ReactiveFindByIdOperation.java, spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/ReactiveFindByIdOperationSupport.java, spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/ReactiveInsertByIdOperationSupport.java, spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/ReactiveRemoveByIdOperation.java, spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/ReactiveRemoveByIdOperationSupport.java, spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/ReactiveReplaceByIdOperationSupport.java, spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/ReactiveTemplateSupport.java, spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/ReactiveUpsertByIdOperationSupport.java, spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/TemplateSupport.java, spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/mapping/CouchbaseDocument.java, spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/support/OneAndAllIdReactive.java
=> Allow id to be type other than String.

spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/ReactiveCouchbaseTemplate.java, spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/TransactionalSupport.java, spring-data-couchbase/src/test/java/org/springframework/data/couchbase/transactions/sdk/SDKTransactionsNonBlockingThreadIntegrationTests.java, spring-data-couchbase/src/test/java/org/springframework/data/couchbase/transactions/sdk/SDKTransactionsSaveIntegrationTests.java
that does not use TransactionMarkerOwner.  As this bypasses
a critical check on whether we are inside a blocking
transaction.
Two new tests in SDKTransactionsSaveIntegrationTests
(reactiveSaveInBlockingTransaction and blockingSaveInBlockingTransaction)
will fail without this, as the .save() does not realise
it's in a transaction.
Adding new tests, for .save() and for performing transactions
in reactor blocking threads.
=> Removing the form of checkForTransactionInThreadLocalStorage

spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/ReactiveCouchbaseTemplate.java, spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/TransactionalSupport.java, spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/mapping/CouchbaseList.java, spring-data-couchbase/src/main/java/org/springframework/data/couchbase/transaction/CouchbaseCallbackTransactionManager.java, spring-data-couchbase/src/test/java/org/springframework/data/couchbase/transactions/CouchbasePersonTransactionReactiveIntegrationTests.java, spring-data-couchbase/src/test/java/org/springframework/data/couchbase/transactions/PersonServiceReactive.java, spring-data-couchbase/src/test/java/org/springframework/data/couchbase/transactions/sdk/SDKTransactionsNonBlockingThreadIntegrationTests.java, spring-data-couchbase/src/test/java/org/springframework/data/couchbase/transactions/sdk/SDKTransactionsSaveIntegrationTests.java
=> Fix block() issues with reactive transactions.

spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java, spring-data-couchbase/src/test/java/org/springframework/data/couchbase/core/mapping/MappingCouchbaseConverterTests.java
=> Allow Id other than String.

spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/query/QueryCriteria.java, spring-data-couchbase/src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateQueryIntegrationTests.java, spring-data-couchbase/src/test/java/org/springframework/data/couchbase/core/query/QueryCriteriaTests.java
=> Fix arrayContaining n1ql generated.

README.adoc, spring-data-couchbase/pom.xml, spring-data-couchbase/src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java, spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/convert/AbstractCouchbaseConverter.java, spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/convert/CouchbaseConverter.java, spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/convert/CouchbaseCustomConversions.java, spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/convert/DecryptingReadingConverter.java, spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/convert/Encrypted.java, spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/convert/EncryptingWritingConverter.java, spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java, spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/convert/OtherConverters.java, spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/mapping/CouchbaseList.java, spring-data-couchbase/src/test/java/org/springframework/data/couchbase/domain/Address.java, spring-data-couchbase/src/test/java/org/springframework/data/couchbase/domain/Config.java, spring-data-couchbase/src/test/java/org/springframework/data/couchbase/domain/UserEncrypted.java, spring-data-couchbase/src/test/java/org/springframework/data/couchbase/domain/UserEncryptedRepository.java, spring-data-couchbase/src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryFieldLevelEncryptionIntegrationTests.java
Note that an @Encrypted property object that contains an @Encrypted property is
not supported and will result in an exception.
Closes #763.
=> Field Level Encryption Support.

spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/convert/DecryptingReadingConverter.java, spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/convert/EncryptingWritingConverter.java, spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java
=> Fix up FLE support.

spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/ReactiveFindByQueryOperationSupport.java, spring-data-couchbase/src/test/java/org/springframework/data/couchbase/transactions/CouchbaseTransactionalRepositoryCollectionIntegrationTests.java
=> Fix collections on transaction query.

spring-data-couchbase/src/test/java/org/springframework/data/couchbase/transactions/CouchbaseTransactionalRepositoryCollectionIntegrationTests.java
=> Fix test class.

src/main/java/org/springframework/data/couchbase/core/convert/join/N1qlJoinResolver.java
=> Fix handling of collections in N1qlJoinResolver.

src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryFieldLevelEncryptionIntegrationTests.java
This removes the need for @Bean methods to be called (in other methods) in AbstractCouchbaseConfiguration.
Closes #1557.
=> Fix config bean dependencies.

pom.xml, src/main/java/org/springframework/data/couchbase/core/ReactiveInsertByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveRemoveByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveReplaceByIdOperationSupport.java
=> Bump Couchbase SDK to 3.4.0.

src/main/asciidoc/fieldlevelencryption.adoc, src/main/asciidoc/index.adoc
=> Add Field Level Encryption Documentation.

src/main/asciidoc/fieldlevelencryption.adoc
From what I understand, this is the opposite no ?
Data is encrypted on write in Couchbase, and decrypted when reading it
=> Typo in field encryption doc

src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java, src/main/java/org/springframework/data/couchbase/core/convert/AbstractCouchbaseConverter.java, src/main/java/org/springframework/data/couchbase/core/convert/BooleanToEnumConverterFactory.java, src/main/java/org/springframework/data/couchbase/core/convert/ConverterHasNoConversion.java, src/main/java/org/springframework/data/couchbase/core/convert/CouchbaseCustomConversions.java, src/main/java/org/springframework/data/couchbase/core/convert/CouchbasePropertyValueConverterFactory.java, src/main/java/org/springframework/data/couchbase/core/convert/CryptoConverter.java, src/main/java/org/springframework/data/couchbase/core/convert/IntegerToEnumConverterFactory.java, src/main/java/org/springframework/data/couchbase/core/convert/JsonValueConverter.java, src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java, src/main/java/org/springframework/data/couchbase/core/convert/OtherConverters.java, src/main/java/org/springframework/data/couchbase/core/convert/StringToEnumConverterFactory.java, src/test/java/org/springframework/data/couchbase/cache/CouchbaseCacheIntegrationTests.java, src/test/java/org/springframework/data/couchbase/domain/AirportJsonValue.java, src/test/java/org/springframework/data/couchbase/domain/AirportJsonValueRepository.java, src/test/java/org/springframework/data/couchbase/domain/AirportJsonValuedObject.java, src/test/java/org/springframework/data/couchbase/domain/EBTurbulenceCategory.java, src/test/java/org/springframework/data/couchbase/domain/EITurbulenceCategory.java, src/test/java/org/springframework/data/couchbase/domain/EJsonCreatorTurbulenceCategory.java, src/test/java/org/springframework/data/couchbase/domain/ETurbulenceCategory.java, src/test/java/org/springframework/data/couchbase/domain/Person.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java, src/test/java/org/springframework/data/couchbase/repository/query/CouchbaseRepositoryQueryCollectionIntegrationTests.java
Implement the @ JsonValue annotation with a property-value converter.
Closes #1617.
=> Add suport for JsonValue annotation on Enums.

src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java, src/main/java/org/springframework/data/couchbase/core/convert/AbstractCouchbaseConverter.java, src/main/java/org/springframework/data/couchbase/core/convert/CouchbasePropertyValueConverterFactory.java, src/main/java/org/springframework/data/couchbase/core/convert/CryptoConverter.java, src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java, src/main/java/org/springframework/data/couchbase/core/convert/OtherConverters.java, src/test/java/org/springframework/data/couchbase/domain/Address.java, src/test/java/org/springframework/data/couchbase/domain/ETurbulenceCategory.java, src/test/java/org/springframework/data/couchbase/domain/UserEncrypted.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryFieldLevelEncryptionIntegrationTests.java
The key changes are at lines 141 and 145 of CryptoConverter.
(a) use objectMapper to encode strings instead of just escaping and adding quotes; and
(b) use context.getConverter().writeInternalRoot() to serialize instead of 
relying on context.read(value).toString()) which relies on the entity object having a toString() that produces json.
Closes #1621.
=> Fix serialization for field level encryption.

src/main/java/org/springframework/data/couchbase/core/convert/BooleanToEnumConverterFactory.java, src/main/java/org/springframework/data/couchbase/core/convert/CouchbasePropertyValueConverterFactory.java, src/main/java/org/springframework/data/couchbase/core/convert/IntegerToEnumConverterFactory.java, src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java, src/main/java/org/springframework/data/couchbase/core/convert/StringToEnumConverterFactory.java
=> Fix javadoc errors introduced by 1621.

src/main/java/org/springframework/data/couchbase/core/ReactiveCouchbaseTemplate.java
=> Restore protected visibility to potentiallyConvertRuntimeException.

src/main/java/org/springframework/data/couchbase/core/ReactiveFindByIdOperationSupport.java, src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateKeyValueIntegrationTests.java
=> Use getAndTouch only when annotation attribute touchOnRead=true.

src/test/java/org/springframework/data/couchbase/domain/UserAnnotatedTouchOnRead.java
=> Refresh test entity class.

src/main/asciidoc/entity.adoc, src/main/asciidoc/template.adoc, src/main/java/org/springframework/data/couchbase/core/ExecutableInsertByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ExecutableRemoveByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ExecutableReplaceByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ExecutableUpsertByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveInsertByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveRemoveByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveReplaceByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveUpsertByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/mapping/Document.java, src/main/java/org/springframework/data/couchbase/core/query/OptionsBuilder.java, src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateKeyValueIntegrationTests.java, src/test/java/org/springframework/data/couchbase/core/ReactiveCouchbaseTemplateKeyValueIntegrationTests.java, src/test/java/org/springframework/data/couchbase/domain/PersonWithDurability.java, src/test/java/org/springframework/data/couchbase/domain/PersonWithDurability2.java, src/test/java/org/springframework/data/couchbase/domain/UserAnnotatedDurability.java, src/test/java/org/springframework/data/couchbase/domain/UserAnnotatedPersistTo.java, src/test/java/org/springframework/data/couchbase/domain/UserAnnotatedReplicateTo.java, src/test/java/org/springframework/data/couchbase/transactions/CouchbaseTransactionalUnsettableParametersIntegrationTests.java
Added support of the PersistTo, ReplicateTo, and DurabilityLevel via @Document annotation.
Closes #1486
=> Durability via Annotations

src/main/java/com/querydsl/couchbase/document/CouchbaseDocumentSerializer.java, src/main/java/org/springframework/data/couchbase/repository/support/BasicQuery.java, src/main/java/org/springframework/data/couchbase/repository/support/SpringDataCouchbaseQuery.java, src/main/java/org/springframework/data/couchbase/repository/support/SpringDataCouchbaseQuerySupport.java, src/test/java/org/springframework/data/couchbase/repository/query/CouchbaseRepositoryQuerydslIntegrationTests.java
Add support of the QueryDSL sorting.
closes #1363
=> QueryDSL Sorting Support

src/main/java/org/springframework/data/couchbase/core/ExecutableFindByIdOperation.java, src/main/java/org/springframework/data/couchbase/core/ExecutableFindByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveFindByIdOperation.java, src/main/java/org/springframework/data/couchbase/core/ReactiveFindByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/support/WithLock.java, src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateKeyValueIntegrationTests.java, src/test/java/org/springframework/data/couchbase/core/ReactiveCouchbaseTemplateKeyValueIntegrationTests.java
Added support of the read locks via `withLock()` operation chaining. 
closes #1059
=> Added support of the read locks

src/main/asciidoc/template.adoc, src/main/java/org/springframework/data/couchbase/core/CouchbaseExceptionTranslator.java, src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplate.java, src/main/java/org/springframework/data/couchbase/core/ExecutableMutateInByIdOperation.java, src/main/java/org/springframework/data/couchbase/core/ExecutableMutateInByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/FluentCouchbaseOperations.java, src/main/java/org/springframework/data/couchbase/core/ReactiveCouchbaseTemplate.java, src/main/java/org/springframework/data/couchbase/core/ReactiveFluentCouchbaseOperations.java, src/main/java/org/springframework/data/couchbase/core/ReactiveMutateInByIdOperation.java, src/main/java/org/springframework/data/couchbase/core/ReactiveMutateInByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/query/OptionsBuilder.java, src/main/java/org/springframework/data/couchbase/core/support/WithMutateInOptions.java, src/main/java/org/springframework/data/couchbase/core/support/WithMutateInPaths.java, src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateKeyValueIntegrationTests.java, src/test/java/org/springframework/data/couchbase/core/ReactiveCouchbaseTemplateKeyValueIntegrationTests.java, src/test/java/org/springframework/data/couchbase/domain/MutableUser.java
Initial Support of the Sub-Document Operations. As of now, only basic mutations are supported 
- upsert
- replace
- remove
- insert
The change introduces new `ReactiveMutateInByIdOperation` and `ExecutableMutateInByIdOperation` operations which give the ability to use the Sub-Document Operations via chained fluent API.
For example
```java
couchbaseTemplate.mutateInById(MutableUser.class)
.withInsertPaths("roles", "subuser.firstname")
.withRemovePaths("address.city")
.withUpsertPaths("firstname")
.withReplacePaths("address.street")
.one(mutableUser);
```
Mutation operations support Durability, Expiray, and Concurrency Control (CAS).
Closes #1659
=> Added Sub-Document mutations support

pom.xml, src/main/java/org/springframework/data/couchbase/core/ReactiveRemoveByQueryOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/query/N1QLQuery.java, src/main/java/org/springframework/data/couchbase/core/query/OptionsBuilder.java, src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateKeyValueIntegrationTests.java, src/test/java/org/springframework/data/couchbase/repository/query/N1qlQueryCreatorTests.java, src/test/java/org/springframework/data/couchbase/util/JavaIntegrationTests.java
Requires some refactoring around @Stability.Internal APIs. Also fixed a test to get it to pass.
Closes #1661,#1662.
=> Bump couchbase sdk to 3_4_3.

src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java, src/main/java/org/springframework/data/couchbase/core/convert/OtherConverters.java, src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateKeyValueIntegrationTests.java, src/test/java/org/springframework/data/couchbase/domain/User.java, src/test/java/org/springframework/data/couchbase/repository/query/StringN1qlQueryCreatorTests.java
=> Provide JsonNode converter.

src/main/java/org/springframework/data/couchbase/core/ReactiveCouchbaseTemplate.java, src/test/java/org/springframework/data/couchbase/core/ReactiveCouchbaseTemplateConcurrencyTests.java
DynamicProxyable repositories can overwrite PseudoArgs object.
When DynamicProxyable repositories are used in heavily concurrent environments, the ReactiveCouchbaseTemplate can overwrite the PseudoArgs object, resulting in null scope, collection and options values. This causes queries to fail unpredictably.
Closes #1684.
=> ReactiveCouchbaseTemplate can overwrite PseudoArgs.

src/main/java/org/springframework/data/couchbase/core/query/QueryCriteria.java
Issue #1707. I extracted duplicated code fragment into a new method "private void checkAndAddToCriteriaChain()". The previous test cases are working and there is no need to add new cased as I did only refactoring.
=> Move duplicate code in QueryCriteria to new method.

src/main/java/org/springframework/data/couchbase/core/convert/CouchbaseCustomConversions.java
Register CouchbaseDocument and CouchbaseList as simple types (datastore supported) to get rid of conversation warning messages.
Closes #1700.
=> Register Couchbase Types with Conversion Services.

src/main/asciidoc/entity.adoc, src/main/asciidoc/index.adoc, src/main/java/org/springframework/data/couchbase/core/ExecutableInsertByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ExecutableMutateInByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ExecutableRemoveByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ExecutableReplaceByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ExecutableUpsertByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveInsertByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveMutateInByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveRemoveByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveReplaceByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/ReactiveUpsertByIdOperationSupport.java, src/main/java/org/springframework/data/couchbase/core/mapping/BasicCouchbasePersistentEntity.java, src/main/java/org/springframework/data/couchbase/core/mapping/CouchbasePersistentEntity.java, src/main/java/org/springframework/data/couchbase/core/mapping/Document.java, src/main/java/org/springframework/data/couchbase/core/mapping/Durability.java, src/main/java/org/springframework/data/couchbase/core/query/OptionsBuilder.java, src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateKeyValueIntegrationTests.java, src/test/java/org/springframework/data/couchbase/core/mapping/BasicCouchbasePersistentEntityTests.java, src/test/java/org/springframework/data/couchbase/domain/UserAnnotatedDurabilityExpression.java
Added `@Durability` annotation and added support for expression-based durability levels.
Currently, `@Durability`  can not be set via annotating the insert/update methods and repositories, so only Document level durability assignment works.
Closes #1063.
=> Expression Based Durability Levels

src/main/java/org/springframework/data/couchbase/repository/support/SimpleCouchbaseRepository.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryKeyValueIntegrationTests.java
=> Pass entity in repository delete(entity) and deleteAll(entities).

README.adoc
=> Links updated for issue-tracker and create-a-new-issue section.

src/main/asciidoc/configuration.adoc
=> Fix repository links in documentation.

src/main/asciidoc/caching.adoc
=> Fix Typo in Cache Documentation.

src/main/java/org/springframework/data/couchbase/core/convert/AbstractCouchbaseConverter.java, src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java, src/main/java/org/springframework/data/couchbase/core/index/QueryIndexResolver.java, src/main/java/org/springframework/data/couchbase/core/query/Query.java, src/main/java/org/springframework/data/couchbase/core/query/StringQuery.java, src/main/java/org/springframework/data/couchbase/repository/query/AbstractCouchbaseQueryBase.java, src/test/java/org/springframework/data/couchbase/core/mapping/BasicCouchbasePersistentEntityTests.java, src/test/java/org/springframework/data/couchbase/core/mapping/BasicCouchbasePersistentPropertyTests.java
=> ClassTypeInformation is now deprecated.

src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java, src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateQueryIntegrationTests.java, src/test/java/org/springframework/data/couchbase/domain/PersonWithMaps.java
=> Try Object.class if cannot get persistent entity for class.

src/main/java/org/springframework/data/couchbase/core/ReactiveCouchbaseTemplate.java, src/test/java/org/springframework/data/couchbase/transactions/sdk/SDKTransactionsSaveIntegrationTests.java, src/test/java/org/springframework/data/couchbase/transactions/util/TransactionTestUtil.java
=> Allow template.save() to find if it is in a transaction.

src/main/java/org/springframework/data/couchbase/core/query/StringQuery.java, src/main/java/org/springframework/data/couchbase/repository/query/StringBasedN1qlQueryParser.java, src/test/java/org/springframework/data/couchbase/repository/query/StringN1qlQueryCreatorTests.java
=> Restore StringQuery constructor that takes only string.

src/main/java/org/springframework/data/couchbase/core/convert/DefaultCouchbaseTypeMapper.java, src/main/java/org/springframework/data/couchbase/core/index/CouchbasePersistentEntityIndexResolver.java, src/main/java/org/springframework/data/couchbase/core/query/Query.java, src/main/java/org/springframework/data/couchbase/repository/query/N1qlMutateQueryCreator.java, src/main/java/org/springframework/data/couchbase/repository/query/OldN1qlQueryCreator.java, src/main/java/org/springframework/data/couchbase/repository/query/StringBasedN1qlQueryParser.java, src/main/java/org/springframework/data/couchbase/repository/query/support/N1qlUtils.java, src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateKeyValueIntegrationTests.java, src/test/java/org/springframework/data/couchbase/core/mapping/MappingCouchbaseConverterTests.java, src/test/java/org/springframework/data/couchbase/domain/UserNoAlias.java
If the configuration getType() or the @TypeAlias is an empty string, then do not add the typeKey:typeAlias property when storing documents, and do not add the typeKey=typeAlias property on queries - including removeByQuery.
=> Option to not use typeKey=typeAlias property and predicate.

src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateQueryIntegrationTests.java, src/test/java/org/springframework/data/couchbase/domain/AssessmentDO.java, src/test/java/org/springframework/data/couchbase/domain/MutableUser.java, src/test/java/org/springframework/data/couchbase/domain/PersonValue.java, src/test/java/org/springframework/data/couchbase/domain/PersonWithMaps.java, src/test/java/org/springframework/data/couchbase/domain/SubscriptionToken.java, src/test/java/org/springframework/data/couchbase/domain/UserSubmission.java, src/test/java/org/springframework/data/couchbase/domain/UserSubmissionAnnotated.java, src/test/java/org/springframework/data/couchbase/domain/UserSubmissionProjected.java, src/test/java/org/springframework/data/couchbase/domain/UserSubmissionUnannotated.java, src/test/java/org/springframework/data/couchbase/transactions/AfterTransactionAssertion.java, src/test/java/org/springframework/data/couchbase/transactions/CouchbasePersonTransactionIntegrationTests.java, src/test/java/org/springframework/data/couchbase/transactions/CouchbasePersonTransactionReactiveIntegrationTests.java
=> Remove lombok from test cases.

src/main/asciidoc/configuration.adoc
=> Add Doc to Change Couchbase SDK Version.

src/main/java/org/springframework/data/couchbase/repository/support/DynamicInvocationHandler.java, src/main/java/org/springframework/data/couchbase/repository/support/FindMethod.java, src/test/java/org/springframework/data/couchbase/domain/AirlineRepository.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java
Allow non-exact (isAssignableFrom) argument matching for methods called by DyanmicProxyable. If there are exactly two candidates, and one returns an Iterable and the other returns a List, use the method that returns the List.  This is due to
CouchbaseRepository defining findAll() methods as List<?>, while PagingAndSortyRepository defines findAll() to return an Iterable. This needs to be addressed separately.
Closes #1818.
=> Allow non-exact argument type matching for DynamicProxyable.

pom.xml
=> Bump Couchbase SDK to 3.4.10 on 5.1.x

src/main/java/org/springframework/data/couchbase/core/ReactiveCouchbaseTemplate.java, src/main/java/org/springframework/data/couchbase/repository/support/CouchbaseRepositoryBase.java, src/main/java/org/springframework/data/couchbase/repository/support/SimpleCouchbaseRepository.java, src/main/java/org/springframework/data/couchbase/repository/support/SimpleReactiveCouchbaseRepository.java, src/test/java/org/springframework/data/couchbase/domain/ReactiveAirportMustScopeRepository.java, src/test/java/org/springframework/data/couchbase/repository/query/ReactiveCouchbaseRepositoryQueryCollectionIntegrationTests.java
The issue was introduced when the Mono.deferContextual() was added to determine if the save() is in a transaction. It may be executing in a different thread when the PseudoArgs (scope, collection, and options) are retrieved ThreadLocal. This change ensures scope and collection are retrieved, but options are ignored and discarded.
Closes #1838.
=> Fix ThreadLocal Issue with Repository Save.

src/main/java/org/springframework/data/couchbase/repository/query/StringBasedN1qlQueryParser.java, src/test/java/org/springframework/data/couchbase/domain/UserRepository.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java
Just use the converted value as-is (in case of boolean or Number) enum value.
Closes #1837.
=> Don't use String version of enum parameters.

src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java, src/main/java/org/springframework/data/couchbase/core/convert/CouchbaseCustomConversions.java
=> Provide Default CouchbaseCustomConversions with Enum Converters.

src/main/java/org/springframework/data/couchbase/repository/support/SpringDataCouchbaseQuery.java, src/test/java/org/springframework/data/couchbase/domain/AirlineCollectioned.java, src/test/java/org/springframework/data/couchbase/domain/AirlineCollectionedRepository.java, src/test/java/org/springframework/data/couchbase/repository/query/CouchbaseRepositoryCollectionQuerydslIntegrationTests.java, src/test/java/org/springframework/data/couchbase/util/CollectionAwareDefaultScopeIntegrationTests.java
Fixed issue with querying documents annotated with @Collection with QuerydslPredicateExecutor.
Closes #1866
=> QuerydslPredicateExecutor Does not Respect collection of the document.

src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java, src/test/java/org/springframework/data/couchbase/domain/MyPerson.java, src/test/java/org/springframework/data/couchbase/domain/MyPersonRepository.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java
=> Fix regression in saving  and reading Object type properties

src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java, src/main/java/org/springframework/data/couchbase/core/convert/AbstractCouchbaseConverter.java, src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java, src/test/java/org/springframework/data/couchbase/domain/AbstractingMappingCouchbaseConverter.java, src/test/java/org/springframework/data/couchbase/domain/Config.java, src/test/java/org/springframework/data/couchbase/domain/CustomMappingCouchbaseConverter.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseAbstractRepositoryIntegrationTests.java
Propagated CouchbaseCustomConverters bean into MappingConverter.
Just a polishing fix to propagate CouchbaseCustomConversions directly to MappingCouchbaseConverter -> AbstractCouchbaseConverter , So that we won't have to set it explicitly. Fixes https://github.com/spring-projects/spring-data-couchbase/issues/1850 .
=> Propagated CouchbaseCustomConverters bean into MappingConverter

src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java
Added functionality to register custom converters in the list + cleaned up the code a little. Let me know if I have to add test cases for this. Not added yet as the change was small. Fixes https://github.com/spring-projects/spring-data-couchbase/issues/1876.
=> Added functionality to add customConverters.

pom.xml, src/test/java/org/springframework/data/couchbase/util/JavaIntegrationTests.java
=> Bump Couchbase Java SDK to 3.5.2 in 5.3.0.

src/main/java/org/springframework/data/couchbase/core/mapping/event/AuditingEventListener.java, src/test/java/org/springframework/data/couchbase/core/query/ReactiveCouchbaseTemplateQueryCollectionIntegrationTests.java
=> Change AuditingEventListener Constructor Signature.

pom.xml
Tested with juliojgd's reproducer on https://github.com/spring-projects/spring-boot/issues/39740
Closes #1909.
=> Remove the "provided" from querydsl dependency.

src/main/java/org/springframework/data/couchbase/repository/support/CouchbaseRepositoryFactory.java, src/main/java/org/springframework/data/couchbase/repository/support/CrudMethodMetadataPostProcessor.java, src/main/java/org/springframework/data/couchbase/repository/support/ReactiveCouchbaseRepositoryFactory.java
Make CrudMethodMetadataPostProcessor public and make factory
getTargetRepository() not final (so factory can be extended)
This is to ease extending spring-data-couchbase.
Closes #1877.
=> Make CrudMethodMetadataPostProcessor public.

pom.xml
=> Remove javax.inject dependency from 5.1.x.

pom.xml
=> Remove javax.inject dependency in 5.0.x

src/main/java/org/springframework/data/couchbase/core/convert/OtherConverters.java, src/main/java/org/springframework/data/couchbase/core/convert/translation/JacksonTranslationService.java, src/main/java/org/springframework/data/couchbase/core/mapping/CouchbaseSimpleTypes.java, src/test/java/org/springframework/data/couchbase/core/mapping/MappingCouchbaseConverterTests.java, src/test/java/org/springframework/data/couchbase/domain/BigAirline.java, src/test/java/org/springframework/data/couchbase/domain/BigAirlineRepository.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryKeyValueIntegrationTests.java, src/test/java/org/springframework/data/couchbase/repository/query/CouchbaseRepositoryQueryCollectionIntegrationTests.java, src/test/java/org/springframework/data/couchbase/repository/query/CouchbaseRepositoryQuerydslIntegrationTests.java
Also be able to read BigDecimal and BigInteger that were written as String. Also does not lose precision by converting BigDecimal to double in the transcoder.
Closes #1611.
=> Store BigDecimal and BigInteger as Numbers like the Java SDK does.

pom.xml, src/main/java/org/springframework/data/couchbase/repository/support/CouchbaseAnnotationProcessor.java, src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateKeyValueIntegrationTests.java, src/test/java/org/springframework/data/couchbase/core/query/QueryCriteriaTests.java, src/test/java/org/springframework/data/couchbase/domain/BigAirlineRepository.java
CouchbaseAnnotationProcessor will provide a warning and skip generation if javax.inject is not present.
Closes #1929.
=> Exclude javax.inject and CB AnnotationProcessor to exit gracefully w/o.

src/main/java/org/springframework/data/couchbase/repository/support/DynamicInvocationHandler.java, src/main/java/org/springframework/data/couchbase/repository/support/SimpleCouchbaseRepository.java, src/main/java/org/springframework/data/couchbase/repository/support/SimpleReactiveCouchbaseRepository.java, src/test/java/org/springframework/data/couchbase/repository/query/CouchbaseRepositoryQueryCollectionIntegrationTests.java, src/test/java/org/springframework/data/couchbase/repository/query/ReactiveCouchbaseRepositoryQueryCollectionIntegrationTests.java
1) Handle list argument for deleteAllById for DynamicProxy.
2) Hold scopeName and collectionName for multiple calls.
Closes #1939.
=> Handle list argument for deletedAllById for DynamicProxy.

src/test/java/org/springframework/data/couchbase/transactions/CouchbaseTransactionalTemplateCollectionDefaultScopeIntegrationTests.java, src/test/java/org/springframework/data/couchbase/transactions/CouchbaseTransactionalTemplateCollectionIntegrationTests.java, src/test/java/org/springframework/data/couchbase/transactions/CouchbaseTransactionalTemplateIntegrationTests.java, src/test/java/org/springframework/data/couchbase/util/Util.java
=> Fix test for being inside a transaction.

src/main/java/org/springframework/data/couchbase/cache/CouchbaseCache.java, src/main/java/org/springframework/data/couchbase/cache/CouchbaseCacheWriter.java, src/main/java/org/springframework/data/couchbase/cache/DefaultCouchbaseCacheWriter.java, src/test/java/org/springframework/data/couchbase/cache/CacheUser.java, src/test/java/org/springframework/data/couchbase/cache/CouchbaseCacheCollectionTranscoderIntegrationTests.java
=> Add transcoder support on Cache get, putIfAbsent.

src/main/java/org/springframework/data/couchbase/repository/support/FindMethod.java, src/test/java/org/springframework/data/couchbase/domain/ReactiveAirportRepository.java, src/test/java/org/springframework/data/couchbase/repository/ReactiveCouchbaseRepositoryQueryIntegrationTests.java
=> Allow primitive repository args for DynamicProxyable repositories..

ci/clean.sh
This reverts commit 13d39949ad69fba675ea9f7c2c39092411b223d5.
Closes #1975.
=> Revert "Fix ci/clean.sh permission denied. (#1974)"

src/main/java/org/springframework/data/couchbase/repository/query/StringBasedN1qlQueryParser.java, src/test/java/org/springframework/data/couchbase/domain/AirportRepository.java, src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java
=> Fix number of parameters in string based @Query queries.

src/main/java/org/springframework/data/couchbase/transaction/CouchbaseCallbackTransactionManager.java, src/main/java/org/springframework/data/couchbase/transaction/CouchbaseResourceHolder.java, src/main/java/org/springframework/data/couchbase/transaction/CouchbaseResourceOwner.java, src/test/java/org/springframework/data/couchbase/transactions/CouchbasePersonTransactionReactiveIntegrationTests.java, src/test/java/org/springframework/data/couchbase/transactions/PersonServiceReactive.java, src/test/java/org/springframework/data/couchbase/util/Util.java
=> Propagate SecurityContext into @Transactional methods.

src/main/java/org/springframework/data/couchbase/transaction/CouchbaseCallbackTransactionManager.java
=> Fix to sdc_1944 to handle null SecurityContext.

src/main/java/org/springframework/data/couchbase/cache/CouchbaseCache.java, src/main/java/org/springframework/data/couchbase/cache/CouchbaseCacheConfiguration.java
=> Fix javadoc in couchbase cache.

pom.xml, src/main/java/org/springframework/data/couchbase/repository/support/CouchbaseAnnotationProcessor.java, src/main/resources/META-INF/services/javax.annotation.processing.Processor
To use querydsl, the spring application will need to add a dependency
<dependency>
<groupId>com.querydsl</groupId>
<artifactId>querydsl-apt</artifactId>
<version>${querydsl}</version>
<classifier>jakarta</classifier>
<scope>provided</scope>
</dependency>
And explicitly specify CouchbasseAnnotationProcessor
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-compiler-plugin</artifactId>
<executions>
<execution>
<id>annotation-processing</id>
<phase>generate-sources</phase>
<goals>
<goal>compile</goal>
</goals>
<configuration>
<proc>only</proc>
<annotationProcessors>
<annotationProcessor>org.springframework.data.couchbase.repository.support.CouchbaseAnnotationProcessor</annotationProcessor>
</annotationProcessors> …
=> Remove dependency on javax.inject from querydsl.

src/main/antora/modules/ROOT/pages/couchbase/configuration.adoc
=> Add compatibility in doc.

pom.xml
=> Bump Couchbase Java SDK to 3.7.7 on 5.4.x.

pom.xml, src/test/java/org/springframework/data/couchbase/repository/query/CouchbaseRepositoryQuerydslIntegrationTests.java
because of CVE-2024-49203.
Closes #2409.
=> Switch to OpenFeign QueryDSL

src/main/java/org/springframework/data/couchbase/cache/CouchbaseCacheManager.java, src/main/java/org/springframework/data/couchbase/cache/CouchbaseCacheWriter.java, src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplate.java, src/main/java/org/springframework/data/couchbase/core/ExecutableFindByAnalyticsOperation.java, src/main/java/org/springframework/data/couchbase/core/ExecutableFindByQueryOperation.java, src/main/java/org/springframework/data/couchbase/core/convert/BooleanToEnumConverterFactory.java, src/main/java/org/springframework/data/couchbase/core/convert/CouchbaseConversionContext.java, src/main/java/org/springframework/data/couchbase/core/convert/IntegerToEnumConverterFactory.java, src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java, src/main/java/org/springframework/data/couchbase/core/convert/StringToEnumConverterFactory.java, src/main/java/org/springframework/data/couchbase/core/index/CouchbasePersistentEntityIndexResolver.java, src/main/java/org/springframework/data/couchbase/core/query/Meta.java, src/main/java/org/springframework/data/couchbase/core/query/QueryCriteria.java, src/main/java/org/springframework/data/couchbase/repository/query/AbstractCouchbaseQuery.java, src/main/java/org/springframework/data/couchbase/repository/query/AbstractCouchbaseQueryBase.java, src/main/java/org/springframework/data/couchbase/repository/query/AbstractReactiveCouchbaseQuery.java, src/main/java/org/springframework/data/couchbase/repository/support/CouchbaseAnnotationProcessor.java, src/main/java/org/springframework/data/couchbase/repository/support/CrudMethodMetadataPostProcessor.java, src/main/java/org/springframework/data/couchbase/repository/support/SpringDataCouchbaseQuery.java, src/main/java/org/springframework/data/couchbase/repository/support/SpringDataCouchbaseSerializer.java, src/main/java/org/springframework/data/couchbase/transaction/CouchbaseCallbackTransactionManager.java, src/main/java/org/springframework/data/couchbase/transaction/CouchbaseResourceHolder.java, src/main/java/org/springframework/data/couchbase/transaction/CouchbaseTransactionInterceptor.java, src/test/java/org/springframework/data/couchbase/domain/Person.java, src/test/java/org/springframework/data/couchbase/transactions/CouchbaseTransactionalPropagationIntegrationTests.java
=> Use JSpecify annotations for nullability.
