pom.xml
src/main/java/org/springframework/data/couchbase/core/CouchbaseOperations.java
src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplate.java
src/main/java/org/springframework/data/couchbase/template/package-info.java

template will be in same package as 1.x generation, that is "core"

prepare bare template class, use preview of SDK 2.2.0

---

pom.xml
src/main/java/org/springframework/data/couchbase/config/CouchbaseEnvironmentFactoryBean.java
src/main/java/org/springframework/data/couchbase/config/CouchbaseEnvironmentNoShutdownProxy.java
src/main/java/org/springframework/data/couchbase/config/CouchbaseEnvironmentParser.java
src/main/java/org/springframework/data/couchbase/core/CouchbaseOperations.java
src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplate.java
src/main/java/org/springframework/data/couchbase/repository/query/AbstractN1qlBasedQuery.java
src/main/java/org/springframework/data/couchbase/repository/query/N1qlQueryCreator.java
src/main/resources/org/springframework/data/couchbase/config/spring-couchbase-env-2.0.xsd
src/test/java/org/springframework/data/couchbase/config/CouchbaseEnvironmentParserTest.java
src/test/java/org/springframework/data/couchbase/repository/query/AbstractN1qlBasedQueryTest.java
src/test/resources/configurations/couchbaseEnv-bean.xml

ParametrizedQuery is now ParameterizedQuery, a few parameters have been added to the environment parsing, made use of N1QL Functions where newly available.

DATACOUCH-152 - Bump SDK to 2.2.0-dp2 and fix related TODOs.

---

pom.xml
src/integration/java/org/springframework/data/couchbase/core/CouchbaseTemplateTests.java
src/integration/java/org/springframework/data/couchbase/repository/feature/FeatureDetectionRepositoryTests.java
src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java
src/main/java/org/springframework/data/couchbase/config/CouchbaseEnvironmentNoShutdownProxy.java
src/main/java/org/springframework/data/couchbase/core/CouchbaseOperations.java
src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplate.java
src/main/java/org/springframework/data/couchbase/core/convert/translation/TranslationService.java
src/main/java/org/springframework/data/couchbase/repository/query/AbstractN1qlBasedQuery.java
src/main/java/org/springframework/data/couchbase/repository/query/StringN1qlBasedQuery.java
src/main/java/org/springframework/data/couchbase/repository/support/N1qlCouchbaseRepository.java
src/test/java/org/springframework/data/couchbase/repository/query/AbstractN1qlBasedQueryTest.java

Make modifications due to name changing in 2.2.0, the latest stable release of the Couchbase SDK.

DATACOUCH-164 - Use stable Couchbase SDK

---

src/integration/java/org/springframework/data/couchbase/repository/SimpleCouchbaseRepositoryTests.java
src/integration/java/org/springframework/data/couchbase/repository/UserRepository.java
src/main/asciidoc/repository.adoc
src/main/java/org/springframework/data/couchbase/core/view/Query.java
src/main/java/org/springframework/data/couchbase/repository/query/AbstractN1qlBasedQuery.java
src/main/java/org/springframework/data/couchbase/repository/query/PartTreeN1qlBasedQuery.java
src/main/java/org/springframework/data/couchbase/repository/query/StringN1qlBasedQuery.java
src/main/java/org/springframework/data/couchbase/repository/support/CouchbaseRepositoryFactory.java
src/test/java/org/springframework/data/couchbase/repository/query/StringN1QlBasedQueryTest.java
src/test/resources/logback.xml

first pass at having SpEL support in inline N1QL queries

DATACOUCH-166 - Add basic SpEL support

---

src/integration/java/org/springframework/data/couchbase/repository/xmlconfig/XmlItemRepository.java
src/integration/java/org/springframework/data/couchbase/repository/xmlconfig/XmlRepositoryConfigurationTests.java
src/integration/resources/configurations/couchbase-repository-bean.xml
src/main/resources/org/springframework/data/couchbase/config/spring-couchbase-2.0.xsd

@daschl this one will be a prerequisite to PR #77 (a rebase will be needed).

DATACOUCH-174 - Fix declaration of repositories in xml

---

src/integration/java/org/springframework/data/couchbase/repository/SimpleCouchbaseRepositoryTests.java
src/integration/java/org/springframework/data/couchbase/repository/UserRepository.java
src/main/asciidoc/repository.adoc
src/main/java/org/springframework/data/couchbase/core/query/Query.java
src/main/java/org/springframework/data/couchbase/repository/query/StringN1qlBasedQuery.java
src/test/java/org/springframework/data/couchbase/repository/query/StringN1QlBasedQueryTest.java

SpelParser parses the whole statement and prefix for SpEL blocks is now "#{".

DATACOUCH-166 - Improve and simplify SpEL support implementation

---

src/integration/java/org/springframework/data/couchbase/repository/extending/base/RepositoryBaseTest.java
src/integration/java/org/springframework/data/couchbase/repository/extending/base/impl/MyRepository.java
src/integration/java/org/springframework/data/couchbase/repository/extending/base/impl/MyRepositoryImpl.java
src/integration/java/org/springframework/data/couchbase/repository/extending/method/MyItem.java
src/integration/java/org/springframework/data/couchbase/repository/extending/method/MyRepository.java
src/integration/java/org/springframework/data/couchbase/repository/extending/method/MyRepositoryCustom.java
src/integration/java/org/springframework/data/couchbase/repository/extending/method/MyRepositoryImpl.java
src/integration/java/org/springframework/data/couchbase/repository/extending/method/RepositoryCustomMethodTest.java
src/main/asciidoc/repository.adoc

Added an integration test for custom method customization.
Moved the integration test for base class customization.
Put the samples in the documentation in a new "Changing Repository Behaviour" section.

DATACOUCH-189 - Test and document how to change repo implementation

---

src/integration/java/org/springframework/data/couchbase/repository/N1qlPlaceholderTests.java
src/integration/java/org/springframework/data/couchbase/repository/PartyRepository.java
src/main/asciidoc/repository.adoc
src/main/java/org/springframework/data/couchbase/repository/query/AbstractN1qlBasedQuery.java
src/main/java/org/springframework/data/couchbase/repository/query/PartTreeN1qlBasedQuery.java
src/main/java/org/springframework/data/couchbase/repository/query/StringN1qlBasedQuery.java
src/test/resources/logback.xml

@daschl can you review this? :bow:

DATACOUCH-180 - Allow named parameters in inline N1QL queries

---

src/integration/java/org/springframework/data/couchbase/repository/SimpleCouchbaseRepositoryTests.java
src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplate.java
src/main/java/org/springframework/data/couchbase/repository/support/SimpleCouchbaseRepository.java

@daschl I'm interested in what you think about this one

DATACOUCH-212 - Take Version/CAS into account on save

---

src/main/java/org/springframework/data/couchbase/repository/support/IndexManager.java

This should avoid problems when the message changes on the server side
(like in Couchbase Server 4.5).

DATACOUCH-229 - Check N1QL error codes rather than message

---

src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplate.java

This brings better performance when querying large views. Instead of
looping on a synchronously acquired list of documents to produce a list
of entities, the async API can be used internally to:
- query the view
- fetch the documents
- map each document to an entity
- collect into a List
One can then block on that Observable to get and return the List as
usual.
Perf gain has been validated by one of our users. @daschl I'll need a quick review on this one :)

DATACOUCH-228 - Make findByView use async client internally

---

pom.xml
src/integration/resources/configurations/couchbase-consistency.xml
src/integration/resources/configurations/couchbase-multi-bucket-bean.xml
src/integration/resources/configurations/couchbase-repository-bean.xml
src/integration/resources/configurations/couchbase-template-bean.xml
src/integration/resources/configurations/couchbase-template-with-translation-service-bean.xml
src/integration/resources/configurations/couchbase-typekey.xml
src/test/resources/META-INF/beans.xml
src/test/resources/configurations/couchbaseBucket-bean.xml
src/test/resources/configurations/couchbaseCluster-bean.xml
src/test/resources/configurations/couchbaseEnv-bean.xml
src/test/resources/configurations/couchbaseSingleEnv-bean.xml

This commit updates URLs to prefer the https protocol. Redirects are not followed to avoid accidentally expanding intentionally shortened URLs (i.e. if using a URL shortener).
These URLs were switched to an https URL with a 2xx status. While the status was successful, your review is still recommended.
* http://maven.apache.org/xsd/maven-4.0.0.xsd with 1 occurrences migrated to:  
https://maven.apache.org/xsd/maven-4.0.0.xsd ([https](https://maven.apache.org/xsd/maven-4.0.0.xsd) result 200).
* http://www.springframework.org/schema/beans/spring-beans.xsd with 10 occurrences migrated to:  
https://www.springframework.org/schema/beans/spring-beans.xsd ([https](https://www.springframework.org/schema/beans/spring-beans.xsd) result 200).
* …

URL Cleanup

---

src/main/java/org/springframework/data/couchbase/repository/support/SimpleReactiveCouchbaseRepository.java
src/test/java/org/springframework/data/couchbase/repository/SimpleReactiveCouchbaseRepositoryDeleteAllIntegrationTests.java

Plus a test.  I didn't notice that Douglas Six did basically the
same thing in another PR (this was a re-do of an earlier PR - #154 which
didn't quite do what we'd like).  So since I already had it done
and had a test, I closed that PR (#163) and added him to the author
list.
Also - repository.count() raises a NoSuchElementException after you
delete all the documents.  That seems like a bug, but we will deal
with that separately.

DATACOUCH-356 Fix cast issue in deleteAll

---

src/test/java/org/springframework/data/couchbase/domain/Airline.java
src/test/java/org/springframework/data/couchbase/domain/AirlineRepository.java
src/test/java/org/springframework/data/couchbase/repository/query/StringN1qlQueryCreatorMockedTests.java
src/test/java/org/springframework/data/couchbase/repository/query/StringN1qlQueryCreatorTests.java

- [ x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [ x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATACOUCH).
- [ x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [ x] You submit test cases (unit or integration tests) that back your changes.
- [ x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

DATACOUCH-561 - Better Testing for String Query

---

src/main/java/org/springframework/data/couchbase/core/ReactiveInsertByIdOperationSupport.java
src/main/java/org/springframework/data/couchbase/core/ReactiveReplaceByIdOperationSupport.java
src/main/java/org/springframework/data/couchbase/core/ReactiveUpsertByIdOperationSupport.java
src/test/java/org/springframework/data/couchbase/domain/Library.java
src/test/java/org/springframework/data/couchbase/domain/LibraryRepository.java
src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryKeyValueIntegrationTests.java

Add support for saving document with lists and composed objects.
Convert CouchbaseDocument/CouchbaseList to Map/List before saving.
There is another PR for the same ticket (https://github.com/spring-projects/spring-data-couchbase/pull/227) but i would like to propose another approach to solve the problem.

DATACOUCH-560 - Serialization of CouchbaseDocument and CouchbaseList.

---

src/main/java/org/springframework/data/couchbase/core/query/Query.java

DATACOUCH-632 - Fix compilation error introduced in DATACOUCH-603.

---

pom.xml

DATACOUCH-634 - Upgrade Couchbase Java SDK to 3.0.9.

---

pom.xml

DATACOUCH-634 - Upgrade Couchbase Java SDK to 3_0_9.

---

pom.xml

DATACOUCH-660 - Upgrade Couchbase Java SDK to 3.1.0 for 4.2.

---

pom.xml

DATACOUCH-662 Upgrade Couchbase Java SDK to 3.0.10 for 4.1.x.

---

pom.xml

DATACOUCH-663 - Upgrade Couchbase Java SDK to 3.0.10 for 4.0.x.

---

src/main/java/org/springframework/data/couchbase/core/ReactiveReplaceByIdOperationSupport.java
src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateKeyValueIntegrationTests.java
src/test/java/org/springframework/data/couchbase/domain/PersonValue.java
src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryKeyValueIntegrationTests.java

Previously, this was only handled in insert and upsert.

DATACOUCH-666 - Handle immutable entity in replace.

---

src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateKeyValueIntegrationTests.java

DATACOUCH-672 - Reinstate replace expiry tests.

---

src/test/java/org/springframework/data/couchbase/util/JavaIntegrationTests.java
src/test/java/org/springframework/data/couchbase/util/Util.java

Update copyright in two new classes.

DATACOUCH-1048 - Update copyright in two new classes.

---

pom.xml
src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java

Closes #1079.
Original pull request #1098.

Upgrade Couchbase Java SDK to 3.1.3.

---

README.adoc

Closes #1105.
Original pull request #1106.

Update versions to correct values.

---

src/main/java/org/springframework/data/couchbase/core/convert/AbstractCouchbaseConverter.java
src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java
src/main/java/org/springframework/data/couchbase/core/query/QueryCriteria.java
src/test/java/org/springframework/data/couchbase/core/query/QueryCriteriaTests.java
src/test/java/org/springframework/data/couchbase/domain/AirportRepository.java
src/test/java/org/springframework/data/couchbase/domain/Iata.java
src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java

Support enums in AbstractCouchbaseConverter.convertForWriteIfNeeded().
Closes #1069.
Original pull request #1110.

Support enum parameters to repository queries.

---

pom.xml

Upgrade to Couchbase Java SDK 3.1.4.
Closes #1122.
Original pull request #1123.

Upgrade to Couchbase Java SDK 3.1.4.

---

pom.xml

Upgrade Couchbase Java SDK to 3.1.5.

---

pom.xml

Update Couchbase SDK to 3.1.6.
Closes #1157.

Update Couchbase SDK to 3.1.6.

---

src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java
src/test/java/org/springframework/data/couchbase/domain/User.java
src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java

Handle Transient Annotation.

---

src/test/java/org/springframework/data/couchbase/domain/FluxTest.java
src/test/java/org/springframework/data/couchbase/domain/User.java
src/test/java/org/springframework/data/couchbase/domain/UserRepository.java
src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java

Add Transient, Stream and Flux Pair tests.

---

pom.xml

Upgrade Couchbase Java SDK to 3.2.0.

---

pom.xml

Update Couchbase Java SDK to 3.2.1.

---

pom.xml

Update Couchbase Java SDK to 3.1.7.

---

src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplate.java
src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplateSupport.java
src/main/java/org/springframework/data/couchbase/core/ReactiveCouchbaseTemplate.java
src/main/java/org/springframework/data/couchbase/core/ReactiveCouchbaseTemplateSupport.java
src/main/java/org/springframework/data/couchbase/core/convert/join/N1qlJoinResolver.java
src/main/java/org/springframework/data/couchbase/core/query/N1QLQuery.java
src/main/java/org/springframework/data/couchbase/core/query/Query.java
src/test/java/org/springframework/data/couchbase/domain/Address.java
src/test/java/org/springframework/data/couchbase/domain/UserSubmission.java
src/test/java/org/springframework/data/couchbase/domain/UserSubmissionRepository.java
src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java

Support N1QL Join Annotations.

---

src/test/java/org/springframework/data/couchbase/util/ClusterAwareIntegrationTests.java

Fix test failure against mocked.

---

src/main/java/org/springframework/data/couchbase/core/ReactiveFindByIdOperationSupport.java
src/main/java/org/springframework/data/couchbase/core/mapping/BasicCouchbasePersistentEntity.java
src/main/java/org/springframework/data/couchbase/core/mapping/CouchbasePersistentEntity.java
src/test/java/org/springframework/data/couchbase/core/mapping/BasicCouchbasePersistentEntityTests.java

Changes for PR 1223 that I had missed.

---

src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplate.java
src/main/java/org/springframework/data/couchbase/core/ReactiveCouchbaseTemplate.java

Closes #1210.
- [] You submit test cases (unit or integration tests) that back your changes.

Expose TemplateSupport from Template.

---

src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java

Unbean couchbaseObjectMapper().

---

pom.xml

Upgrade Couchbase Java SDK to 3.2.3

---

src/main/java/org/springframework/data/couchbase/repository/query/support/N1qlUtils.java

Fix javadoc reference to Field.

---

src/main/java/org/springframework/data/couchbase/core/query/Query.java
src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateQueryIntegrationTests.java
src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java

Copy sort from pageable to query.

---

src/main/asciidoc/entity.adoc

Fix CasMismatch documentation.

---

src/main/java/org/springframework/data/couchbase/core/ReactiveFindByAnalyticsOperationSupport.java

Make FindByAnalytics count the same as FindByQuery.

---

pom.xml

Bump Couchbase Java SDK to 3_2_5.

---

pom.xml

Bump Couchbase SDK to 3_2_5 on 5_0_x.

---

src/main/java/org/springframework/data/couchbase/cache/CouchbaseCacheConfiguration.java

Fix comment.

---

pom.xml

Make Querydsl dependency "provided".

---

pom.xml

Bump Couchbase Java SDK to 3.2.6.

---

pom.xml
src/test/java/org/springframework/data/couchbase/util/CollectionAwareIntegrationTests.java

Also put quotes around bucket name in CollectionAwareIntegrationTests setup.
Closes #1409.

Bump 4.3.x Couchbase Java SDK to 3.2.6.

---

pom.xml

Bump 4.2.x Couchbase Java SDK to 3.1.8.

---

src/main/java/org/springframework/data/couchbase/core/ReactiveFindByQueryOperationSupport.java
src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java

Count not requiring specific property name.

---

src/test/java/org/springframework/data/couchbase/util/CollectionAwareIntegrationTests.java

Quotes around bucket name in setup for collection tests.

---

pom.xml

Remove explicit dependency on annotations api.

---

pom.xml

Update Couchbase Java SDK to 3.3.0.

---

pom.xml

Update Couchbase SDK to 3.3.0 in main.

---

pom.xml

Upgrade Couchbase Java SDK to 3.2.7 in branch 4.3.x.

---

src/test/java/org/springframework/data/couchbase/repository/query/StringN1qlQueryCreatorTests.java

Fix test compilation issue introduced by bad automerge in cherry-pick.

---

src/main/java/org/springframework/data/couchbase/core/convert/OtherConverters.java

Serialize BigDecimal using toString() instead of toPlainString().

---

src/test/java/org/springframework/data/couchbase/domain/FluxTestIntegrationTests.java
src/test/java/org/springframework/data/couchbase/repository/query/StringN1qlQueryCreatorIntegrationTests.java
src/test/java/org/springframework/data/couchbase/repository/query/StringN1qlQueryCreatorMockedTests.java

Move tests needing server to IntegrationTests.

---

src/main/java/org/springframework/data/couchbase/core/query/StringQuery.java

Fix javadoc error.

---

pom.xml

Use Couchbase Java SDK 3_3_2.

---

src/main/java/org/springframework/data/couchbase/repository/query/AbstractCouchbaseQueryBase.java

After 1490, changes needed so integration tests pass.

---

src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateKeyValueIntegrationTests.java
src/test/java/org/springframework/data/couchbase/core/ReactiveCouchbaseTemplateKeyValueIntegrationTests.java

Fix expiry tests so they are not so sensitive to server expiry timing.

---

spring-data-couchbase/src/main/java/org/springframework/data/couchbase/repository/query/AbstractCouchbaseQueryBase.java

Fix reactive parameter handling.

---

src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java
src/test/java/org/springframework/data/couchbase/core/mapping/MappingCouchbaseConverterTests.java

Allow document ID to be other than String

---

pom.xml

Bump Couchbase Java SDK to 3_3_4 in main.

---

pom.xml
src/test/resources/integration.properties

Bump Couchbase Java SDK to 3_3_4 in 4_4_x.

---

spring-data-couchbase/src/main/java/org/springframework/data/couchbase/core/convert/CouchbaseCustomConversions.java

Fix javadoc from fle merge.

---

pom.xml

Try to fix generation and compilation of query dsl test classes.

---

src/main/java/org/springframework/data/couchbase/core/convert/CryptoConverter.java

Get encrypterAlias from annotation.

---

src/main/java/org/springframework/data/couchbase/core/convert/AbstractCouchbaseConverter.java
src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java
src/main/java/org/springframework/data/couchbase/repository/query/StringBasedN1qlQueryParser.java
src/test/java/org/springframework/data/couchbase/domain/UserSubmissionRepository.java
src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java

Accept entity parameters to repository methods.

---

src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java

Remove deprecated methods from AbstractCouchbaseConfiguration.

---

src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java
src/main/java/org/springframework/data/couchbase/repository/query/StringBasedN1qlQueryParser.java
src/test/java/org/springframework/data/couchbase/domain/UserSubmissionRepository.java
src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java

Handle arguments that are lists.

---

pom.xml

Update Couchbase Java SDK to 3.4.1

---

src/main/java/org/springframework/data/couchbase/core/query/QueryCriteria.java
src/test/java/org/springframework/data/couchbase/core/query/QueryCriteriaTests.java

Use "= true" for TRUE() and "= false" for FALSE().

---

src/main/java/org/springframework/data/couchbase/core/convert/CouchbasePropertyValueConverterFactory.java

Fix copyright year that I broke.

---

src/main/java/org/springframework/data/couchbase/core/ReactiveFindByIdOperationSupport.java
src/test/java/org/springframework/data/couchbase/core/CouchbaseTemplateKeyValueIntegrationTests.java

Take expiry from entity class annotation for getAndTouch.

---

src/test/java/org/springframework/data/couchbase/domain/UserAnnotatedTouchOnRead.java

Add missing test entity class.

---

src/main/asciidoc/transactions.adoc

Mention @Version in transaction documentation.

---

src/test/java/org/springframework/data/couchbase/util/UnmanagedTestCluster.java

Add test file missed in #1661.

---

src/main/java/org/springframework/data/couchbase/config/AbstractCouchbaseConfiguration.java

Eliminate need to override transactionInterceptor bean.

---

src/main/asciidoc/index.adoc

Remove accented character from documentation.

---

src/main/asciidoc/template.adoc

Fix duplicate tag in documentation.

---

src/main/java/org/springframework/data/couchbase/core/ReactiveRemoveByIdOperationSupport.java

Pass cas from oneEntity call to one by id.

---

pom.xml

Bump Couchbase Java SDK to 3.4.4

---

pom.xml

Bump Couchbase Java SDK to 3.4.4.

---

src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java

Use ApplicationContext classloader for MappingCouchbaseConverter.

---

src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java

Use the ApplicationContext class loader for MappingCouchbaseConverter.

---

pom.xml

Bump Couchbase Java SDK to 3.4.5.

---

src/main/java/org/springframework/data/couchbase/core/convert/OtherConverters.java
src/test/java/org/springframework/data/couchbase/core/mapping/MappingCouchbaseConverterTests.java

Add YearMonth converter.

---

src/main/java/org/springframework/data/couchbase/core/convert/OtherConverters.java

Check for nulls.

---

pom.xml
src/test/java/org/springframework/data/couchbase/core/ReactiveCouchbaseTemplateKeyValueIntegrationTests.java

Also add more time for findByIdWithLock case - it must be more than the default timeout of 2.5 seconds.
Closes #1727.

Bump Couchbase Java SDK to 3.4.6.

---

src/main/asciidoc/fieldlevelencryption.adoc

Fix code example for field level encryption.

---

src/main/java/org/springframework/data/couchbase/core/query/QueryCriteria.java
src/test/java/org/springframework/data/couchbase/core/query/QueryCriteriaTests.java

Use only converter for elements of parameter array.

---

pom.xml
src/main/java/org/springframework/data/couchbase/core/ReactiveRangeScanOperationSupport.java

Bump Couchbase Java SDK to 3.4.7.

---

src/test/java/org/springframework/data/couchbase/transactions/sdk/SDKTransactionsSaveIntegrationTests.java

Fix compile error from #1757.

---

pom.xml
src/main/java/org/springframework/data/couchbase/core/ReactiveRangeScanOperationSupport.java

Bump Couchbase SDK to 3_4_7.

---

src/main/asciidoc/configuration.adoc

Add Doc to Change Couchbase SDK Version.

---

src/main/asciidoc/configuration.adoc

Add doc for multiple buckets and heading for overriding SDK.

---

pom.xml

Bump Couchbase SDK to 3_4_9.

---

pom.xml

Bump Couchbase SDK to 3_4_9 on 5_1_x.

---

pom.xml

Bump Couchbase SDK to 3_4_9 on 5_0_x.

---

pom.xml

Set Couchbase Java SDK to 3.4.8.

---

pom.xml

Set Couchbase Java SDK to 3.4.8 on 5.0.x.

---

src/main/java/com/querydsl/couchbase/document/CouchbaseDocumentSerializer.java
src/test/java/org/springframework/data/couchbase/repository/query/CouchbaseRepositoryQuerydslIntegrationTests.java

Fix JDK8 compilation errors introduced by cherry-picking #1363.

---

pom.xml

Bump Couchbase SDK to 3.4.10 on 5.0.x.

---

pom.xml

Bump Couchbase SDK to 3.4.10 on main.

---

pom.xml

Bump Couchbase SDK to 3.4.11.

---

pom.xml

Bump Couchbase SDK to 3.4.11 on 5.0.

---

pom.xml

Bump Couchbase SDK to 3.4.11 on 5.1.

---

.mvn/gradle-enterprise.xml

Disable build cache for codeQL.

---

src/main/java/org/springframework/data/couchbase/core/ReactiveFindByQueryOperationSupport.java

Use scope and collection in transaction in findByQuery.count().

---

pom.xml
src/main/antora/modules/ROOT/pages/couchbase/repository.adoc
src/main/resources/META-INF/services/javax.annotation.processing.Processor

Mark CouchbaseAnnotationProcessor for auto-discovery

---

pom.xml

Bump Couchbase SDK to 3.6.0.

---

pom.xml

Remove javax.inject depdendency.

---

pom.xml

Eliminate javax.inject dependency.

---

pom.xml

Remove dependency on javax.injection.

---

pom.xml

Remove javax.injection dependency, use querydsl classifier jakarta.

---

src/main/java/org/springframework/data/couchbase/repository/support/CouchbaseAnnotationProcessor.java

Restore nullable arg.

---

src/main/java/org/springframework/data/couchbase/core/mapping/event/AuditingEventListener.java

Fix auditing.

---

ci/clean.sh

Fix ci/clean.sh permission denied.

---

pom.xml

Bump Couchbase Java SDK to 3.7.4.

---

pom.xml

Change scope of javax.inject.Inject to compile.

---

src/main/antora/modules/ROOT/pages/couchbase/repository.adoc

Update QueryDSL doc.

---

pom.xml

Bump Couchbase Java SDK to 3.7.7.

---

pom.xml

Bump Couchbase SDK to 3.7.8.

---

pom.xml

Bump Couchbase SDK to 3.7.8 on 6.0.x.

---

pom.xml

Bump Couchbase SDK to 3.8.0 on 6.0.x.

---

src/main/antora/modules/ROOT/pages/couchbase/fieldlevelencryption.adoc

Fix typo in Encryption

---

src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java
src/main/java/org/springframework/data/couchbase/repository/query/StringBasedN1qlQueryParser.java
src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryFieldLevelEncryptionIntegrationTests.java

Project mangled field names.

---

pom.xml

Bump Couchbase SDK to 3.8.2

---

pom.xml
src/main/java/org/springframework/data/couchbase/cache/CouchbaseCacheManager.java
src/main/java/org/springframework/data/couchbase/cache/CouchbaseCacheWriter.java
src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplate.java
src/main/java/org/springframework/data/couchbase/core/ExecutableFindByAnalyticsOperation.java
src/main/java/org/springframework/data/couchbase/core/ExecutableFindByQueryOperation.java
src/main/java/org/springframework/data/couchbase/core/convert/BooleanToEnumConverterFactory.java
src/main/java/org/springframework/data/couchbase/core/convert/CouchbaseConversionContext.java
src/main/java/org/springframework/data/couchbase/core/convert/IntegerToEnumConverterFactory.java
src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java
src/main/java/org/springframework/data/couchbase/core/convert/StringToEnumConverterFactory.java
src/main/java/org/springframework/data/couchbase/core/index/CouchbasePersistentEntityIndexResolver.java
src/main/java/org/springframework/data/couchbase/core/query/Meta.java
src/main/java/org/springframework/data/couchbase/core/query/QueryCriteria.java
src/main/java/org/springframework/data/couchbase/repository/query/AbstractCouchbaseQuery.java
src/main/java/org/springframework/data/couchbase/repository/query/AbstractCouchbaseQueryBase.java
src/main/java/org/springframework/data/couchbase/repository/query/AbstractReactiveCouchbaseQuery.java
src/main/java/org/springframework/data/couchbase/repository/support/CouchbaseAnnotationProcessor.java
src/main/java/org/springframework/data/couchbase/repository/support/CrudMethodMetadataPostProcessor.java
src/main/java/org/springframework/data/couchbase/repository/support/SpringDataCouchbaseQuery.java
src/main/java/org/springframework/data/couchbase/repository/support/SpringDataCouchbaseSerializer.java
src/main/java/org/springframework/data/couchbase/transaction/CouchbaseCallbackTransactionManager.java
src/main/java/org/springframework/data/couchbase/transaction/CouchbaseResourceHolder.java
src/main/java/org/springframework/data/couchbase/transaction/CouchbaseTransactionInterceptor.java
src/test/java/org/springframework/data/couchbase/domain/Person.java
src/test/java/org/springframework/data/couchbase/transactions/CouchbaseTransactionalPropagationIntegrationTests.java

Use JSpecify annotations for nullability.

---

pom.xml
src/main/java/org/springframework/data/couchbase/cache/CouchbaseCacheManager.java
src/main/java/org/springframework/data/couchbase/cache/CouchbaseCacheWriter.java
src/main/java/org/springframework/data/couchbase/core/CouchbaseTemplate.java
src/main/java/org/springframework/data/couchbase/core/ExecutableFindByAnalyticsOperation.java
src/main/java/org/springframework/data/couchbase/core/ExecutableFindByQueryOperation.java
src/main/java/org/springframework/data/couchbase/core/convert/BooleanToEnumConverterFactory.java
src/main/java/org/springframework/data/couchbase/core/convert/CouchbaseConversionContext.java
src/main/java/org/springframework/data/couchbase/core/convert/IntegerToEnumConverterFactory.java
src/main/java/org/springframework/data/couchbase/core/convert/MappingCouchbaseConverter.java
src/main/java/org/springframework/data/couchbase/core/convert/StringToEnumConverterFactory.java
src/main/java/org/springframework/data/couchbase/core/index/CouchbasePersistentEntityIndexResolver.java
src/main/java/org/springframework/data/couchbase/core/query/Meta.java
src/main/java/org/springframework/data/couchbase/core/query/QueryCriteria.java
src/main/java/org/springframework/data/couchbase/repository/query/AbstractCouchbaseQuery.java
src/main/java/org/springframework/data/couchbase/repository/query/AbstractCouchbaseQueryBase.java
src/main/java/org/springframework/data/couchbase/repository/query/AbstractReactiveCouchbaseQuery.java
src/main/java/org/springframework/data/couchbase/repository/support/CouchbaseAnnotationProcessor.java
src/main/java/org/springframework/data/couchbase/repository/support/CrudMethodMetadataPostProcessor.java
src/main/java/org/springframework/data/couchbase/repository/support/SpringDataCouchbaseQuery.java
src/main/java/org/springframework/data/couchbase/repository/support/SpringDataCouchbaseSerializer.java
src/main/java/org/springframework/data/couchbase/transaction/CouchbaseCallbackTransactionManager.java
src/main/java/org/springframework/data/couchbase/transaction/CouchbaseResourceHolder.java
src/main/java/org/springframework/data/couchbase/transaction/CouchbaseTransactionInterceptor.java
src/test/java/org/springframework/data/couchbase/domain/Person.java
src/test/java/org/springframework/data/couchbase/transactions/CouchbaseTransactionalPropagationIntegrationTests.java

Use JSpecify for nullability.

---

pom.xml

Bump Couchbase SDK to 3.8.3.

---

pom.xml

Remove unnecessary dependency jspecify.

---

pom.xml
src/test/java/org/springframework/data/couchbase/repository/CouchbaseRepositoryQueryIntegrationTests.java

Bump Couchbase SDK to 3.9.1
